package com.huatai.common.ctp;

import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import org.bridj.ann.Name;
import org.bridj.cpp.CPPObject;

/**
 * \u8d27\u5e01\u8d28\u62bc\u540c\u6b65<br>
 * <i>native declaration : line 8111</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Name("CThostFtdcSyncFundMortgageField")
@Library("thosttraderapi")
public class CThostFtdcSyncFundMortgageField extends StructObject {
	static {
		BridJ.register();
	}
	
	/**
	 * \u8d27\u5e01\u8d28\u62bc\u6d41\u6c34\u53f7<br>
	 * C type : TThostFtdcDepositSeqNoType
	 */
	@Array({ 15 })
	@Field(0)
	public Pointer<Byte> MortgageSeqNo() {
		return io.getPointerField(this, 0);
	}
	
	/**
	 * \u7ecf\u7eaa\u516c\u53f8\u4ee3\u7801<br>
	 * C type : TThostFtdcBrokerIDType
	 */
	@Array({ 11 })
	@Field(1)
	public Pointer<Byte> BrokerID() {
		return io.getPointerField(this, 1);
	}
	
	/**
	 * \u6295\u8d44\u8005\u4ee3\u7801<br>
	 * C type : TThostFtdcInvestorIDType
	 */
	@Array({ 13 })
	@Field(2)
	public Pointer<Byte> InvestorID() {
		return io.getPointerField(this, 2);
	}
	
	/**
	 * \u6e90\u5e01\u79cd<br>
	 * C type : TThostFtdcCurrencyIDType
	 */
	@Array({ 4 })
	@Field(3)
	public Pointer<Byte> FromCurrencyID() {
		return io.getPointerField(this, 3);
	}
	
	/**
	 * \u8d28\u62bc\u91d1\u989d<br>
	 * C type : TThostFtdcMoneyType
	 */
	@Field(4)
	public double MortgageAmount() {
		return io.getDoubleField(this, 4);
	}
	
	/**
	 * \u8d28\u62bc\u91d1\u989d<br>
	 * C type : TThostFtdcMoneyType
	 */
	@Field(4)
	public CThostFtdcSyncFundMortgageField MortgageAmount(double MortgageAmount) {
		io.setDoubleField(this, 4, MortgageAmount);
		return this;
	}
	
	/**
	 * \u76ee\u6807\u5e01\u79cd<br>
	 * C type : TThostFtdcCurrencyIDType
	 */
	@Array({ 4 })
	@Field(5)
	public Pointer<Byte> ToCurrencyID() {
		return io.getPointerField(this, 5);
	}
	
	public CThostFtdcSyncFundMortgageField() {
		super();
	}
	
	public CThostFtdcSyncFundMortgageField(Pointer<? extends CPPObject> pointer) {
		super(pointer);
	}
}
