package com.huatai.common.ctp;

import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import org.bridj.ann.Name;
import org.bridj.cpp.CPPObject;

/**
 * \u67e5\u8be2\u524d\u7f6e\u72b6\u6001<br>
 * <i>native declaration : line 8622</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Name("CThostFtdcQryFrontStatusField")
@Library("thosttraderapi")
public class CThostFtdcQryFrontStatusField extends StructObject {
	static {
		BridJ.register();
	}
	
	/**
	 * \u524d\u7f6e\u7f16\u53f7<br>
	 * C type : TThostFtdcFrontIDType
	 */
	@Field(0)
	public int FrontID() {
		return io.getIntField(this, 0);
	}
	
	/**
	 * \u524d\u7f6e\u7f16\u53f7<br>
	 * C type : TThostFtdcFrontIDType
	 */
	@Field(0)
	public CThostFtdcQryFrontStatusField FrontID(int FrontID) {
		io.setIntField(this, 0, FrontID);
		return this;
	}
	
	public CThostFtdcQryFrontStatusField() {
		super();
	}
	
	public CThostFtdcQryFrontStatusField(Pointer<? extends CPPObject> pointer) {
		super(pointer);
	}
}
