package com.huatai.common.ctp;

import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import org.bridj.ann.Name;
import org.bridj.cpp.CPPObject;

/**
 * \u707e\u5907\u4e2d\u5fc3\u4ea4\u6613\u6743\u9650<br>
 * <i>native declaration : line 13855</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Name("CThostFtdcUserRightsAssignField")
@Library("thosttraderapi")
public class CThostFtdcUserRightsAssignField extends StructObject {
	static {
		BridJ.register();
	}
	
	/**
	 * \u5e94\u7528\u5355\u5143\u4ee3\u7801<br>
	 * C type : TThostFtdcBrokerIDType
	 */
	@Array({ 11 })
	@Field(0)
	public Pointer<Byte> BrokerID() {
		return io.getPointerField(this, 0);
	}
	
	/**
	 * \u7528\u6237\u4ee3\u7801<br>
	 * C type : TThostFtdcUserIDType
	 */
	@Array({ 16 })
	@Field(1)
	public Pointer<Byte> UserID() {
		return io.getPointerField(this, 1);
	}
	
	/**
	 * \u4ea4\u6613\u4e2d\u5fc3\u4ee3\u7801<br>
	 * C type : TThostFtdcDRIdentityIDType
	 */
	@Field(2)
	public int DRIdentityID() {
		return io.getIntField(this, 2);
	}
	
	/**
	 * \u4ea4\u6613\u4e2d\u5fc3\u4ee3\u7801<br>
	 * C type : TThostFtdcDRIdentityIDType
	 */
	@Field(2)
	public CThostFtdcUserRightsAssignField DRIdentityID(int DRIdentityID) {
		io.setIntField(this, 2, DRIdentityID);
		return this;
	}
	
	public CThostFtdcUserRightsAssignField() {
		super();
	}
	
	public CThostFtdcUserRightsAssignField(Pointer<? extends CPPObject> pointer) {
		super(pointer);
	}
}
