package com.huatai.common.ctp;

import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import org.bridj.ann.Name;
import org.bridj.cpp.CPPObject;

/**
 * \u884c\u60c5\u57fa\u7840\u5c5e\u6027<br>
 * <i>native declaration : line 10219</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Name("CThostFtdcMarketDataBaseField")
@Library("thosttraderapi")
public class CThostFtdcMarketDataBaseField extends StructObject {
	static {
		BridJ.register();
	}
	
	/**
	 * \u4ea4\u6613\u65e5<br>
	 * C type : TThostFtdcDateType
	 */
	@Array({ 9 })
	@Field(0)
	public Pointer<Byte> TradingDay() {
		return io.getPointerField(this, 0);
	}
	
	/**
	 * \u4e0a\u6b21\u7ed3\u7b97\u4ef7<br>
	 * C type : TThostFtdcPriceType
	 */
	@Field(1)
	public double PreSettlementPrice() {
		return io.getDoubleField(this, 1);
	}
	
	/**
	 * \u4e0a\u6b21\u7ed3\u7b97\u4ef7<br>
	 * C type : TThostFtdcPriceType
	 */
	@Field(1)
	public CThostFtdcMarketDataBaseField PreSettlementPrice(double PreSettlementPrice) {
		io.setDoubleField(this, 1, PreSettlementPrice);
		return this;
	}
	
	/**
	 * \u6628\u6536\u76d8<br>
	 * C type : TThostFtdcPriceType
	 */
	@Field(2)
	public double PreClosePrice() {
		return io.getDoubleField(this, 2);
	}
	
	/**
	 * \u6628\u6536\u76d8<br>
	 * C type : TThostFtdcPriceType
	 */
	@Field(2)
	public CThostFtdcMarketDataBaseField PreClosePrice(double PreClosePrice) {
		io.setDoubleField(this, 2, PreClosePrice);
		return this;
	}
	
	/**
	 * \u6628\u6301\u4ed3\u91cf<br>
	 * C type : TThostFtdcLargeVolumeType
	 */
	@Field(3)
	public double PreOpenInterest() {
		return io.getDoubleField(this, 3);
	}
	
	/**
	 * \u6628\u6301\u4ed3\u91cf<br>
	 * C type : TThostFtdcLargeVolumeType
	 */
	@Field(3)
	public CThostFtdcMarketDataBaseField PreOpenInterest(double PreOpenInterest) {
		io.setDoubleField(this, 3, PreOpenInterest);
		return this;
	}
	
	/**
	 * \u6628\u865a\u5b9e\u5ea6<br>
	 * C type : TThostFtdcRatioType
	 */
	@Field(4)
	public double PreDelta() {
		return io.getDoubleField(this, 4);
	}
	
	/**
	 * \u6628\u865a\u5b9e\u5ea6<br>
	 * C type : TThostFtdcRatioType
	 */
	@Field(4)
	public CThostFtdcMarketDataBaseField PreDelta(double PreDelta) {
		io.setDoubleField(this, 4, PreDelta);
		return this;
	}
	
	public CThostFtdcMarketDataBaseField() {
		super();
	}
	
	public CThostFtdcMarketDataBaseField(Pointer<? extends CPPObject> pointer) {
		super(pointer);
	}
}
