package com.huatai.common.ctp;

import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import org.bridj.ann.Name;
import org.bridj.cpp.CPPObject;

/**
 * \u6267\u884c\u5ba3\u544a<br>
 * <i>native declaration : line 9024</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Name("CThostFtdcExecOrderField")
@Library("thosttraderapi")
public class CThostFtdcExecOrderField extends StructObject {
	static {
		BridJ.register();
	}
	
	/**
	 * \u7ecf\u7eaa\u516c\u53f8\u4ee3\u7801<br>
	 * C type : TThostFtdcBrokerIDType
	 */
	@Array({ 11 })
	@Field(0)
	public Pointer<Byte> BrokerID() {
		return io.getPointerField(this, 0);
	}
	
	/**
	 * \u6295\u8d44\u8005\u4ee3\u7801<br>
	 * C type : TThostFtdcInvestorIDType
	 */
	@Array({ 13 })
	@Field(1)
	public Pointer<Byte> InvestorID() {
		return io.getPointerField(this, 1);
	}
	
	/**
	 * \u5408\u7ea6\u4ee3\u7801<br>
	 * C type : TThostFtdcInstrumentIDType
	 */
	@Array({ 31 })
	@Field(2)
	public Pointer<Byte> InstrumentID() {
		return io.getPointerField(this, 2);
	}
	
	/**
	 * \u6267\u884c\u5ba3\u544a\u5f15\u7528<br>
	 * C type : TThostFtdcOrderRefType
	 */
	@Array({ 13 })
	@Field(3)
	public Pointer<Byte> ExecOrderRef() {
		return io.getPointerField(this, 3);
	}
	
	/**
	 * \u7528\u6237\u4ee3\u7801<br>
	 * C type : TThostFtdcUserIDType
	 */
	@Array({ 16 })
	@Field(4)
	public Pointer<Byte> UserID() {
		return io.getPointerField(this, 4);
	}
	
	/**
	 * \u6570\u91cf<br>
	 * C type : TThostFtdcVolumeType
	 */
	@Field(5)
	public int Volume() {
		return io.getIntField(this, 5);
	}
	
	/**
	 * \u6570\u91cf<br>
	 * C type : TThostFtdcVolumeType
	 */
	@Field(5)
	public CThostFtdcExecOrderField Volume(int Volume) {
		io.setIntField(this, 5, Volume);
		return this;
	}
	
	/**
	 * \u8bf7\u6c42\u7f16\u53f7<br>
	 * C type : TThostFtdcRequestIDType
	 */
	@Field(6)
	public int RequestID() {
		return io.getIntField(this, 6);
	}
	
	/**
	 * \u8bf7\u6c42\u7f16\u53f7<br>
	 * C type : TThostFtdcRequestIDType
	 */
	@Field(6)
	public CThostFtdcExecOrderField RequestID(int RequestID) {
		io.setIntField(this, 6, RequestID);
		return this;
	}
	
	/**
	 * \u4e1a\u52a1\u5355\u5143<br>
	 * C type : TThostFtdcBusinessUnitType
	 */
	@Array({ 21 })
	@Field(7)
	public Pointer<Byte> BusinessUnit() {
		return io.getPointerField(this, 7);
	}
	
	/**
	 * \u5f00\u5e73\u6807\u5fd7<br>
	 * C type : TThostFtdcOffsetFlagType
	 */
	@Field(8)
	public byte OffsetFlag() {
		return io.getByteField(this, 8);
	}
	
	/**
	 * \u5f00\u5e73\u6807\u5fd7<br>
	 * C type : TThostFtdcOffsetFlagType
	 */
	@Field(8)
	public CThostFtdcExecOrderField OffsetFlag(byte OffsetFlag) {
		io.setByteField(this, 8, OffsetFlag);
		return this;
	}
	
	/**
	 * \u6295\u673a\u5957\u4fdd\u6807\u5fd7<br>
	 * C type : TThostFtdcHedgeFlagType
	 */
	@Field(9)
	public byte HedgeFlag() {
		return io.getByteField(this, 9);
	}
	
	/**
	 * \u6295\u673a\u5957\u4fdd\u6807\u5fd7<br>
	 * C type : TThostFtdcHedgeFlagType
	 */
	@Field(9)
	public CThostFtdcExecOrderField HedgeFlag(byte HedgeFlag) {
		io.setByteField(this, 9, HedgeFlag);
		return this;
	}
	
	/**
	 * \u6267\u884c\u7c7b\u578b<br>
	 * C type : TThostFtdcActionTypeType
	 */
	@Field(10)
	public byte ActionType() {
		return io.getByteField(this, 10);
	}
	
	/**
	 * \u6267\u884c\u7c7b\u578b<br>
	 * C type : TThostFtdcActionTypeType
	 */
	@Field(10)
	public CThostFtdcExecOrderField ActionType(byte ActionType) {
		io.setByteField(this, 10, ActionType);
		return this;
	}
	
	/**
	 * \u4fdd\u7559\u5934\u5bf8\u7533\u8bf7\u7684\u6301\u4ed3\u65b9\u5411<br>
	 * C type : TThostFtdcPosiDirectionType
	 */
	@Field(11)
	public byte PosiDirection() {
		return io.getByteField(this, 11);
	}
	
	/**
	 * \u4fdd\u7559\u5934\u5bf8\u7533\u8bf7\u7684\u6301\u4ed3\u65b9\u5411<br>
	 * C type : TThostFtdcPosiDirectionType
	 */
	@Field(11)
	public CThostFtdcExecOrderField PosiDirection(byte PosiDirection) {
		io.setByteField(this, 11, PosiDirection);
		return this;
	}
	
	/**
	 * \u671f\u6743\u884c\u6743\u540e\u662f\u5426\u4fdd\u7559\u671f\u8d27\u5934\u5bf8\u7684\u6807\u8bb0<br>
	 * C type : TThostFtdcExecOrderPositionFlagType
	 */
	@Field(12)
	public byte ReservePositionFlag() {
		return io.getByteField(this, 12);
	}
	
	/**
	 * \u671f\u6743\u884c\u6743\u540e\u662f\u5426\u4fdd\u7559\u671f\u8d27\u5934\u5bf8\u7684\u6807\u8bb0<br>
	 * C type : TThostFtdcExecOrderPositionFlagType
	 */
	@Field(12)
	public CThostFtdcExecOrderField ReservePositionFlag(byte ReservePositionFlag) {
		io.setByteField(this, 12, ReservePositionFlag);
		return this;
	}
	
	/**
	 * \u671f\u6743\u884c\u6743\u540e\u751f\u6210\u7684\u5934\u5bf8\u662f\u5426\u81ea\u52a8\u5e73\u4ed3<br>
	 * C type : TThostFtdcExecOrderCloseFlagType
	 */
	@Field(13)
	public byte CloseFlag() {
		return io.getByteField(this, 13);
	}
	
	/**
	 * \u671f\u6743\u884c\u6743\u540e\u751f\u6210\u7684\u5934\u5bf8\u662f\u5426\u81ea\u52a8\u5e73\u4ed3<br>
	 * C type : TThostFtdcExecOrderCloseFlagType
	 */
	@Field(13)
	public CThostFtdcExecOrderField CloseFlag(byte CloseFlag) {
		io.setByteField(this, 13, CloseFlag);
		return this;
	}
	
	/**
	 * \u672c\u5730\u6267\u884c\u5ba3\u544a\u7f16\u53f7<br>
	 * C type : TThostFtdcOrderLocalIDType
	 */
	@Array({ 13 })
	@Field(14)
	public Pointer<Byte> ExecOrderLocalID() {
		return io.getPointerField(this, 14);
	}
	
	/**
	 * \u4ea4\u6613\u6240\u4ee3\u7801<br>
	 * C type : TThostFtdcExchangeIDType
	 */
	@Array({ 9 })
	@Field(15)
	public Pointer<Byte> ExchangeID() {
		return io.getPointerField(this, 15);
	}
	
	/**
	 * \u4f1a\u5458\u4ee3\u7801<br>
	 * C type : TThostFtdcParticipantIDType
	 */
	@Array({ 11 })
	@Field(16)
	public Pointer<Byte> ParticipantID() {
		return io.getPointerField(this, 16);
	}
	
	/**
	 * \u5ba2\u6237\u4ee3\u7801<br>
	 * C type : TThostFtdcClientIDType
	 */
	@Array({ 11 })
	@Field(17)
	public Pointer<Byte> ClientID() {
		return io.getPointerField(this, 17);
	}
	
	/**
	 * \u5408\u7ea6\u5728\u4ea4\u6613\u6240\u7684\u4ee3\u7801<br>
	 * C type : TThostFtdcExchangeInstIDType
	 */
	@Array({ 31 })
	@Field(18)
	public Pointer<Byte> ExchangeInstID() {
		return io.getPointerField(this, 18);
	}
	
	/**
	 * \u4ea4\u6613\u6240\u4ea4\u6613\u5458\u4ee3\u7801<br>
	 * C type : TThostFtdcTraderIDType
	 */
	@Array({ 21 })
	@Field(19)
	public Pointer<Byte> TraderID() {
		return io.getPointerField(this, 19);
	}
	
	/**
	 * \u5b89\u88c5\u7f16\u53f7<br>
	 * C type : TThostFtdcInstallIDType
	 */
	@Field(20)
	public int InstallID() {
		return io.getIntField(this, 20);
	}
	
	/**
	 * \u5b89\u88c5\u7f16\u53f7<br>
	 * C type : TThostFtdcInstallIDType
	 */
	@Field(20)
	public CThostFtdcExecOrderField InstallID(int InstallID) {
		io.setIntField(this, 20, InstallID);
		return this;
	}
	
	/**
	 * \u6267\u884c\u5ba3\u544a\u63d0\u4ea4\u72b6\u6001<br>
	 * C type : TThostFtdcOrderSubmitStatusType
	 */
	@Field(21)
	public byte OrderSubmitStatus() {
		return io.getByteField(this, 21);
	}
	
	/**
	 * \u6267\u884c\u5ba3\u544a\u63d0\u4ea4\u72b6\u6001<br>
	 * C type : TThostFtdcOrderSubmitStatusType
	 */
	@Field(21)
	public CThostFtdcExecOrderField OrderSubmitStatus(byte OrderSubmitStatus) {
		io.setByteField(this, 21, OrderSubmitStatus);
		return this;
	}
	
	/**
	 * \u62a5\u5355\u63d0\u793a\u5e8f\u53f7<br>
	 * C type : TThostFtdcSequenceNoType
	 */
	@Field(22)
	public int NotifySequence() {
		return io.getIntField(this, 22);
	}
	
	/**
	 * \u62a5\u5355\u63d0\u793a\u5e8f\u53f7<br>
	 * C type : TThostFtdcSequenceNoType
	 */
	@Field(22)
	public CThostFtdcExecOrderField NotifySequence(int NotifySequence) {
		io.setIntField(this, 22, NotifySequence);
		return this;
	}
	
	/**
	 * \u4ea4\u6613\u65e5<br>
	 * C type : TThostFtdcDateType
	 */
	@Array({ 9 })
	@Field(23)
	public Pointer<Byte> TradingDay() {
		return io.getPointerField(this, 23);
	}
	
	/**
	 * \u7ed3\u7b97\u7f16\u53f7<br>
	 * C type : TThostFtdcSettlementIDType
	 */
	@Field(24)
	public int SettlementID() {
		return io.getIntField(this, 24);
	}
	
	/**
	 * \u7ed3\u7b97\u7f16\u53f7<br>
	 * C type : TThostFtdcSettlementIDType
	 */
	@Field(24)
	public CThostFtdcExecOrderField SettlementID(int SettlementID) {
		io.setIntField(this, 24, SettlementID);
		return this;
	}
	
	/**
	 * \u6267\u884c\u5ba3\u544a\u7f16\u53f7<br>
	 * C type : TThostFtdcExecOrderSysIDType
	 */
	@Array({ 21 })
	@Field(25)
	public Pointer<Byte> ExecOrderSysID() {
		return io.getPointerField(this, 25);
	}
	
	/**
	 * \u62a5\u5355\u65e5\u671f<br>
	 * C type : TThostFtdcDateType
	 */
	@Array({ 9 })
	@Field(26)
	public Pointer<Byte> InsertDate() {
		return io.getPointerField(this, 26);
	}
	
	/**
	 * \u63d2\u5165\u65f6\u95f4<br>
	 * C type : TThostFtdcTimeType
	 */
	@Array({ 9 })
	@Field(27)
	public Pointer<Byte> InsertTime() {
		return io.getPointerField(this, 27);
	}
	
	/**
	 * \u64a4\u9500\u65f6\u95f4<br>
	 * C type : TThostFtdcTimeType
	 */
	@Array({ 9 })
	@Field(28)
	public Pointer<Byte> CancelTime() {
		return io.getPointerField(this, 28);
	}
	
	/**
	 * \u6267\u884c\u7ed3\u679c<br>
	 * C type : TThostFtdcExecResultType
	 */
	@Field(29)
	public byte ExecResult() {
		return io.getByteField(this, 29);
	}
	
	/**
	 * \u6267\u884c\u7ed3\u679c<br>
	 * C type : TThostFtdcExecResultType
	 */
	@Field(29)
	public CThostFtdcExecOrderField ExecResult(byte ExecResult) {
		io.setByteField(this, 29, ExecResult);
		return this;
	}
	
	/**
	 * \u7ed3\u7b97\u4f1a\u5458\u7f16\u53f7<br>
	 * C type : TThostFtdcParticipantIDType
	 */
	@Array({ 11 })
	@Field(30)
	public Pointer<Byte> ClearingPartID() {
		return io.getPointerField(this, 30);
	}
	
	/**
	 * \u5e8f\u53f7<br>
	 * C type : TThostFtdcSequenceNoType
	 */
	@Field(31)
	public int SequenceNo() {
		return io.getIntField(this, 31);
	}
	
	/**
	 * \u5e8f\u53f7<br>
	 * C type : TThostFtdcSequenceNoType
	 */
	@Field(31)
	public CThostFtdcExecOrderField SequenceNo(int SequenceNo) {
		io.setIntField(this, 31, SequenceNo);
		return this;
	}
	
	/**
	 * \u524d\u7f6e\u7f16\u53f7<br>
	 * C type : TThostFtdcFrontIDType
	 */
	@Field(32)
	public int FrontID() {
		return io.getIntField(this, 32);
	}
	
	/**
	 * \u524d\u7f6e\u7f16\u53f7<br>
	 * C type : TThostFtdcFrontIDType
	 */
	@Field(32)
	public CThostFtdcExecOrderField FrontID(int FrontID) {
		io.setIntField(this, 32, FrontID);
		return this;
	}
	
	/**
	 * \u4f1a\u8bdd\u7f16\u53f7<br>
	 * C type : TThostFtdcSessionIDType
	 */
	@Field(33)
	public int SessionID() {
		return io.getIntField(this, 33);
	}
	
	/**
	 * \u4f1a\u8bdd\u7f16\u53f7<br>
	 * C type : TThostFtdcSessionIDType
	 */
	@Field(33)
	public CThostFtdcExecOrderField SessionID(int SessionID) {
		io.setIntField(this, 33, SessionID);
		return this;
	}
	
	/**
	 * \u7528\u6237\u7aef\u4ea7\u54c1\u4fe1\u606f<br>
	 * C type : TThostFtdcProductInfoType
	 */
	@Array({ 11 })
	@Field(34)
	public Pointer<Byte> UserProductInfo() {
		return io.getPointerField(this, 34);
	}
	
	/**
	 * \u72b6\u6001\u4fe1\u606f<br>
	 * C type : TThostFtdcErrorMsgType
	 */
	@Array({ 81 })
	@Field(35)
	public Pointer<Byte> StatusMsg() {
		return io.getPointerField(this, 35);
	}
	
	/**
	 * \u64cd\u4f5c\u7528\u6237\u4ee3\u7801<br>
	 * C type : TThostFtdcUserIDType
	 */
	@Array({ 16 })
	@Field(36)
	public Pointer<Byte> ActiveUserID() {
		return io.getPointerField(this, 36);
	}
	
	/**
	 * \u7ecf\u7eaa\u516c\u53f8\u62a5\u5355\u7f16\u53f7<br>
	 * C type : TThostFtdcSequenceNoType
	 */
	@Field(37)
	public int BrokerExecOrderSeq() {
		return io.getIntField(this, 37);
	}
	
	/**
	 * \u7ecf\u7eaa\u516c\u53f8\u62a5\u5355\u7f16\u53f7<br>
	 * C type : TThostFtdcSequenceNoType
	 */
	@Field(37)
	public CThostFtdcExecOrderField BrokerExecOrderSeq(int BrokerExecOrderSeq) {
		io.setIntField(this, 37, BrokerExecOrderSeq);
		return this;
	}
	
	public CThostFtdcExecOrderField() {
		super();
	}
	
	public CThostFtdcExecOrderField(Pointer<? extends CPPObject> pointer) {
		super(pointer);
	}
}
