package com.huatai.common.ctp;

import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import org.bridj.ann.Name;
import org.bridj.cpp.CPPObject;

/**
 * \u67e5\u8be2\u7ba1\u7406\u7528\u6237\u529f\u80fd\u6743\u9650<br>
 * <i>native declaration : line 8591</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Name("CThostFtdcQrySuperUserFunctionField")
@Library("thosttraderapi")
public class CThostFtdcQrySuperUserFunctionField extends StructObject {
	static {
		BridJ.register();
	}
	
	/**
	 * \u7528\u6237\u4ee3\u7801<br>
	 * C type : TThostFtdcUserIDType
	 */
	@Array({ 16 })
	@Field(0)
	public Pointer<Byte> UserID() {
		return io.getPointerField(this, 0);
	}
	
	public CThostFtdcQrySuperUserFunctionField() {
		super();
	}
	
	public CThostFtdcQrySuperUserFunctionField(Pointer<? extends CPPObject> pointer) {
		super(pointer);
	}
}
