package com.huatai.common.ctp;

import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import org.bridj.ann.Name;
import org.bridj.cpp.CPPObject;

/**
 * \u884c\u60c5\u6700\u65b0\u6210\u4ea4\u5c5e\u6027<br>
 * <i>native declaration : line 10255</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Name("CThostFtdcMarketDataLastMatchField")
@Library("thosttraderapi")
public class CThostFtdcMarketDataLastMatchField extends StructObject {
	static {
		BridJ.register();
	}
	
	/**
	 * \u6700\u65b0\u4ef7<br>
	 * C type : TThostFtdcPriceType
	 */
	@Field(0)
	public double LastPrice() {
		return io.getDoubleField(this, 0);
	}
	
	/**
	 * \u6700\u65b0\u4ef7<br>
	 * C type : TThostFtdcPriceType
	 */
	@Field(0)
	public CThostFtdcMarketDataLastMatchField LastPrice(double LastPrice) {
		io.setDoubleField(this, 0, LastPrice);
		return this;
	}
	
	/**
	 * \u6570\u91cf<br>
	 * C type : TThostFtdcVolumeType
	 */
	@Field(1)
	public int Volume() {
		return io.getIntField(this, 1);
	}
	
	/**
	 * \u6570\u91cf<br>
	 * C type : TThostFtdcVolumeType
	 */
	@Field(1)
	public CThostFtdcMarketDataLastMatchField Volume(int Volume) {
		io.setIntField(this, 1, Volume);
		return this;
	}
	
	/**
	 * \u6210\u4ea4\u91d1\u989d<br>
	 * C type : TThostFtdcMoneyType
	 */
	@Field(2)
	public double Turnover() {
		return io.getDoubleField(this, 2);
	}
	
	/**
	 * \u6210\u4ea4\u91d1\u989d<br>
	 * C type : TThostFtdcMoneyType
	 */
	@Field(2)
	public CThostFtdcMarketDataLastMatchField Turnover(double Turnover) {
		io.setDoubleField(this, 2, Turnover);
		return this;
	}
	
	/**
	 * \u6301\u4ed3\u91cf<br>
	 * C type : TThostFtdcLargeVolumeType
	 */
	@Field(3)
	public double OpenInterest() {
		return io.getDoubleField(this, 3);
	}
	
	/**
	 * \u6301\u4ed3\u91cf<br>
	 * C type : TThostFtdcLargeVolumeType
	 */
	@Field(3)
	public CThostFtdcMarketDataLastMatchField OpenInterest(double OpenInterest) {
		io.setDoubleField(this, 3, OpenInterest);
		return this;
	}
	
	public CThostFtdcMarketDataLastMatchField() {
		super();
	}
	
	public CThostFtdcMarketDataLastMatchField(Pointer<? extends CPPObject> pointer) {
		super(pointer);
	}
}
