package com.huatai.common.ctp;

import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import org.bridj.ann.Name;
import org.bridj.cpp.CPPObject;

/**
 * \u4ea4\u6613\u6240\u62a5\u5355\u63d2\u5165\u5931\u8d25<br>
 * <i>native declaration : line 7756</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Name("CThostFtdcExchangeOrderInsertErrorField")
@Library("thosttraderapi")
public class CThostFtdcExchangeOrderInsertErrorField extends StructObject {
	static {
		BridJ.register();
	}
	
	/**
	 * \u4ea4\u6613\u6240\u4ee3\u7801<br>
	 * C type : TThostFtdcExchangeIDType
	 */
	@Array({ 9 })
	@Field(0)
	public Pointer<Byte> ExchangeID() {
		return io.getPointerField(this, 0);
	}
	
	/**
	 * \u4f1a\u5458\u4ee3\u7801<br>
	 * C type : TThostFtdcParticipantIDType
	 */
	@Array({ 11 })
	@Field(1)
	public Pointer<Byte> ParticipantID() {
		return io.getPointerField(this, 1);
	}
	
	/**
	 * \u4ea4\u6613\u6240\u4ea4\u6613\u5458\u4ee3\u7801<br>
	 * C type : TThostFtdcTraderIDType
	 */
	@Array({ 21 })
	@Field(2)
	public Pointer<Byte> TraderID() {
		return io.getPointerField(this, 2);
	}
	
	/**
	 * \u5b89\u88c5\u7f16\u53f7<br>
	 * C type : TThostFtdcInstallIDType
	 */
	@Field(3)
	public int InstallID() {
		return io.getIntField(this, 3);
	}
	
	/**
	 * \u5b89\u88c5\u7f16\u53f7<br>
	 * C type : TThostFtdcInstallIDType
	 */
	@Field(3)
	public CThostFtdcExchangeOrderInsertErrorField InstallID(int InstallID) {
		io.setIntField(this, 3, InstallID);
		return this;
	}
	
	/**
	 * \u672c\u5730\u62a5\u5355\u7f16\u53f7<br>
	 * C type : TThostFtdcOrderLocalIDType
	 */
	@Array({ 13 })
	@Field(4)
	public Pointer<Byte> OrderLocalID() {
		return io.getPointerField(this, 4);
	}
	
	/**
	 * \u9519\u8bef\u4ee3\u7801<br>
	 * C type : TThostFtdcErrorIDType
	 */
	@Field(5)
	public int ErrorID() {
		return io.getIntField(this, 5);
	}
	
	/**
	 * \u9519\u8bef\u4ee3\u7801<br>
	 * C type : TThostFtdcErrorIDType
	 */
	@Field(5)
	public CThostFtdcExchangeOrderInsertErrorField ErrorID(int ErrorID) {
		io.setIntField(this, 5, ErrorID);
		return this;
	}
	
	/**
	 * \u9519\u8bef\u4fe1\u606f<br>
	 * C type : TThostFtdcErrorMsgType
	 */
	@Array({ 81 })
	@Field(6)
	public Pointer<Byte> ErrorMsg() {
		return io.getPointerField(this, 6);
	}
	
	public CThostFtdcExchangeOrderInsertErrorField() {
		super();
	}
	
	public CThostFtdcExchangeOrderInsertErrorField(Pointer<? extends CPPObject> pointer) {
		super(pointer);
	}
}
