package com.huatai.common.ctp;

import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import org.bridj.ann.Name;
import org.bridj.cpp.CPPObject;

/**
 * \u62a5\u4ef7<br>
 * <i>native declaration : line 9615</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Name("CThostFtdcQuoteField")
@Library("thosttraderapi")
public class CThostFtdcQuoteField extends StructObject {
	static {
		BridJ.register();
	}
	
	/**
	 * \u7ecf\u7eaa\u516c\u53f8\u4ee3\u7801<br>
	 * C type : TThostFtdcBrokerIDType
	 */
	@Array({ 11 })
	@Field(0)
	public Pointer<Byte> BrokerID() {
		return io.getPointerField(this, 0);
	}
	
	/**
	 * \u6295\u8d44\u8005\u4ee3\u7801<br>
	 * C type : TThostFtdcInvestorIDType
	 */
	@Array({ 13 })
	@Field(1)
	public Pointer<Byte> InvestorID() {
		return io.getPointerField(this, 1);
	}
	
	/**
	 * \u5408\u7ea6\u4ee3\u7801<br>
	 * C type : TThostFtdcInstrumentIDType
	 */
	@Array({ 31 })
	@Field(2)
	public Pointer<Byte> InstrumentID() {
		return io.getPointerField(this, 2);
	}
	
	/**
	 * \u62a5\u4ef7\u5f15\u7528<br>
	 * C type : TThostFtdcOrderRefType
	 */
	@Array({ 13 })
	@Field(3)
	public Pointer<Byte> QuoteRef() {
		return io.getPointerField(this, 3);
	}
	
	/**
	 * \u7528\u6237\u4ee3\u7801<br>
	 * C type : TThostFtdcUserIDType
	 */
	@Array({ 16 })
	@Field(4)
	public Pointer<Byte> UserID() {
		return io.getPointerField(this, 4);
	}
	
	/**
	 * \u5356\u4ef7\u683c<br>
	 * C type : TThostFtdcPriceType
	 */
	@Field(5)
	public double AskPrice() {
		return io.getDoubleField(this, 5);
	}
	
	/**
	 * \u5356\u4ef7\u683c<br>
	 * C type : TThostFtdcPriceType
	 */
	@Field(5)
	public CThostFtdcQuoteField AskPrice(double AskPrice) {
		io.setDoubleField(this, 5, AskPrice);
		return this;
	}
	
	/**
	 * \u4e70\u4ef7\u683c<br>
	 * C type : TThostFtdcPriceType
	 */
	@Field(6)
	public double BidPrice() {
		return io.getDoubleField(this, 6);
	}
	
	/**
	 * \u4e70\u4ef7\u683c<br>
	 * C type : TThostFtdcPriceType
	 */
	@Field(6)
	public CThostFtdcQuoteField BidPrice(double BidPrice) {
		io.setDoubleField(this, 6, BidPrice);
		return this;
	}
	
	/**
	 * \u5356\u6570\u91cf<br>
	 * C type : TThostFtdcVolumeType
	 */
	@Field(7)
	public int AskVolume() {
		return io.getIntField(this, 7);
	}
	
	/**
	 * \u5356\u6570\u91cf<br>
	 * C type : TThostFtdcVolumeType
	 */
	@Field(7)
	public CThostFtdcQuoteField AskVolume(int AskVolume) {
		io.setIntField(this, 7, AskVolume);
		return this;
	}
	
	/**
	 * \u4e70\u6570\u91cf<br>
	 * C type : TThostFtdcVolumeType
	 */
	@Field(8)
	public int BidVolume() {
		return io.getIntField(this, 8);
	}
	
	/**
	 * \u4e70\u6570\u91cf<br>
	 * C type : TThostFtdcVolumeType
	 */
	@Field(8)
	public CThostFtdcQuoteField BidVolume(int BidVolume) {
		io.setIntField(this, 8, BidVolume);
		return this;
	}
	
	/**
	 * \u8bf7\u6c42\u7f16\u53f7<br>
	 * C type : TThostFtdcRequestIDType
	 */
	@Field(9)
	public int RequestID() {
		return io.getIntField(this, 9);
	}
	
	/**
	 * \u8bf7\u6c42\u7f16\u53f7<br>
	 * C type : TThostFtdcRequestIDType
	 */
	@Field(9)
	public CThostFtdcQuoteField RequestID(int RequestID) {
		io.setIntField(this, 9, RequestID);
		return this;
	}
	
	/**
	 * \u4e1a\u52a1\u5355\u5143<br>
	 * C type : TThostFtdcBusinessUnitType
	 */
	@Array({ 21 })
	@Field(10)
	public Pointer<Byte> BusinessUnit() {
		return io.getPointerField(this, 10);
	}
	
	/**
	 * \u5356\u5f00\u5e73\u6807\u5fd7<br>
	 * C type : TThostFtdcOffsetFlagType
	 */
	@Field(11)
	public byte AskOffsetFlag() {
		return io.getByteField(this, 11);
	}
	
	/**
	 * \u5356\u5f00\u5e73\u6807\u5fd7<br>
	 * C type : TThostFtdcOffsetFlagType
	 */
	@Field(11)
	public CThostFtdcQuoteField AskOffsetFlag(byte AskOffsetFlag) {
		io.setByteField(this, 11, AskOffsetFlag);
		return this;
	}
	
	/**
	 * \u4e70\u5f00\u5e73\u6807\u5fd7<br>
	 * C type : TThostFtdcOffsetFlagType
	 */
	@Field(12)
	public byte BidOffsetFlag() {
		return io.getByteField(this, 12);
	}
	
	/**
	 * \u4e70\u5f00\u5e73\u6807\u5fd7<br>
	 * C type : TThostFtdcOffsetFlagType
	 */
	@Field(12)
	public CThostFtdcQuoteField BidOffsetFlag(byte BidOffsetFlag) {
		io.setByteField(this, 12, BidOffsetFlag);
		return this;
	}
	
	/**
	 * \u5356\u6295\u673a\u5957\u4fdd\u6807\u5fd7<br>
	 * C type : TThostFtdcHedgeFlagType
	 */
	@Field(13)
	public byte AskHedgeFlag() {
		return io.getByteField(this, 13);
	}
	
	/**
	 * \u5356\u6295\u673a\u5957\u4fdd\u6807\u5fd7<br>
	 * C type : TThostFtdcHedgeFlagType
	 */
	@Field(13)
	public CThostFtdcQuoteField AskHedgeFlag(byte AskHedgeFlag) {
		io.setByteField(this, 13, AskHedgeFlag);
		return this;
	}
	
	/**
	 * \u4e70\u6295\u673a\u5957\u4fdd\u6807\u5fd7<br>
	 * C type : TThostFtdcHedgeFlagType
	 */
	@Field(14)
	public byte BidHedgeFlag() {
		return io.getByteField(this, 14);
	}
	
	/**
	 * \u4e70\u6295\u673a\u5957\u4fdd\u6807\u5fd7<br>
	 * C type : TThostFtdcHedgeFlagType
	 */
	@Field(14)
	public CThostFtdcQuoteField BidHedgeFlag(byte BidHedgeFlag) {
		io.setByteField(this, 14, BidHedgeFlag);
		return this;
	}
	
	/**
	 * \u672c\u5730\u62a5\u4ef7\u7f16\u53f7<br>
	 * C type : TThostFtdcOrderLocalIDType
	 */
	@Array({ 13 })
	@Field(15)
	public Pointer<Byte> QuoteLocalID() {
		return io.getPointerField(this, 15);
	}
	
	/**
	 * \u4ea4\u6613\u6240\u4ee3\u7801<br>
	 * C type : TThostFtdcExchangeIDType
	 */
	@Array({ 9 })
	@Field(16)
	public Pointer<Byte> ExchangeID() {
		return io.getPointerField(this, 16);
	}
	
	/**
	 * \u4f1a\u5458\u4ee3\u7801<br>
	 * C type : TThostFtdcParticipantIDType
	 */
	@Array({ 11 })
	@Field(17)
	public Pointer<Byte> ParticipantID() {
		return io.getPointerField(this, 17);
	}
	
	/**
	 * \u5ba2\u6237\u4ee3\u7801<br>
	 * C type : TThostFtdcClientIDType
	 */
	@Array({ 11 })
	@Field(18)
	public Pointer<Byte> ClientID() {
		return io.getPointerField(this, 18);
	}
	
	/**
	 * \u5408\u7ea6\u5728\u4ea4\u6613\u6240\u7684\u4ee3\u7801<br>
	 * C type : TThostFtdcExchangeInstIDType
	 */
	@Array({ 31 })
	@Field(19)
	public Pointer<Byte> ExchangeInstID() {
		return io.getPointerField(this, 19);
	}
	
	/**
	 * \u4ea4\u6613\u6240\u4ea4\u6613\u5458\u4ee3\u7801<br>
	 * C type : TThostFtdcTraderIDType
	 */
	@Array({ 21 })
	@Field(20)
	public Pointer<Byte> TraderID() {
		return io.getPointerField(this, 20);
	}
	
	/**
	 * \u5b89\u88c5\u7f16\u53f7<br>
	 * C type : TThostFtdcInstallIDType
	 */
	@Field(21)
	public int InstallID() {
		return io.getIntField(this, 21);
	}
	
	/**
	 * \u5b89\u88c5\u7f16\u53f7<br>
	 * C type : TThostFtdcInstallIDType
	 */
	@Field(21)
	public CThostFtdcQuoteField InstallID(int InstallID) {
		io.setIntField(this, 21, InstallID);
		return this;
	}
	
	/**
	 * \u62a5\u4ef7\u63d0\u793a\u5e8f\u53f7<br>
	 * C type : TThostFtdcSequenceNoType
	 */
	@Field(22)
	public int NotifySequence() {
		return io.getIntField(this, 22);
	}
	
	/**
	 * \u62a5\u4ef7\u63d0\u793a\u5e8f\u53f7<br>
	 * C type : TThostFtdcSequenceNoType
	 */
	@Field(22)
	public CThostFtdcQuoteField NotifySequence(int NotifySequence) {
		io.setIntField(this, 22, NotifySequence);
		return this;
	}
	
	/**
	 * \u62a5\u4ef7\u63d0\u4ea4\u72b6\u6001<br>
	 * C type : TThostFtdcOrderSubmitStatusType
	 */
	@Field(23)
	public byte OrderSubmitStatus() {
		return io.getByteField(this, 23);
	}
	
	/**
	 * \u62a5\u4ef7\u63d0\u4ea4\u72b6\u6001<br>
	 * C type : TThostFtdcOrderSubmitStatusType
	 */
	@Field(23)
	public CThostFtdcQuoteField OrderSubmitStatus(byte OrderSubmitStatus) {
		io.setByteField(this, 23, OrderSubmitStatus);
		return this;
	}
	
	/**
	 * \u4ea4\u6613\u65e5<br>
	 * C type : TThostFtdcDateType
	 */
	@Array({ 9 })
	@Field(24)
	public Pointer<Byte> TradingDay() {
		return io.getPointerField(this, 24);
	}
	
	/**
	 * \u7ed3\u7b97\u7f16\u53f7<br>
	 * C type : TThostFtdcSettlementIDType
	 */
	@Field(25)
	public int SettlementID() {
		return io.getIntField(this, 25);
	}
	
	/**
	 * \u7ed3\u7b97\u7f16\u53f7<br>
	 * C type : TThostFtdcSettlementIDType
	 */
	@Field(25)
	public CThostFtdcQuoteField SettlementID(int SettlementID) {
		io.setIntField(this, 25, SettlementID);
		return this;
	}
	
	/**
	 * \u62a5\u4ef7\u7f16\u53f7<br>
	 * C type : TThostFtdcOrderSysIDType
	 */
	@Array({ 21 })
	@Field(26)
	public Pointer<Byte> QuoteSysID() {
		return io.getPointerField(this, 26);
	}
	
	/**
	 * \u62a5\u5355\u65e5\u671f<br>
	 * C type : TThostFtdcDateType
	 */
	@Array({ 9 })
	@Field(27)
	public Pointer<Byte> InsertDate() {
		return io.getPointerField(this, 27);
	}
	
	/**
	 * \u63d2\u5165\u65f6\u95f4<br>
	 * C type : TThostFtdcTimeType
	 */
	@Array({ 9 })
	@Field(28)
	public Pointer<Byte> InsertTime() {
		return io.getPointerField(this, 28);
	}
	
	/**
	 * \u64a4\u9500\u65f6\u95f4<br>
	 * C type : TThostFtdcTimeType
	 */
	@Array({ 9 })
	@Field(29)
	public Pointer<Byte> CancelTime() {
		return io.getPointerField(this, 29);
	}
	
	/**
	 * \u62a5\u4ef7\u72b6\u6001<br>
	 * C type : TThostFtdcOrderStatusType
	 */
	@Field(30)
	public byte QuoteStatus() {
		return io.getByteField(this, 30);
	}
	
	/**
	 * \u62a5\u4ef7\u72b6\u6001<br>
	 * C type : TThostFtdcOrderStatusType
	 */
	@Field(30)
	public CThostFtdcQuoteField QuoteStatus(byte QuoteStatus) {
		io.setByteField(this, 30, QuoteStatus);
		return this;
	}
	
	/**
	 * \u7ed3\u7b97\u4f1a\u5458\u7f16\u53f7<br>
	 * C type : TThostFtdcParticipantIDType
	 */
	@Array({ 11 })
	@Field(31)
	public Pointer<Byte> ClearingPartID() {
		return io.getPointerField(this, 31);
	}
	
	/**
	 * \u5e8f\u53f7<br>
	 * C type : TThostFtdcSequenceNoType
	 */
	@Field(32)
	public int SequenceNo() {
		return io.getIntField(this, 32);
	}
	
	/**
	 * \u5e8f\u53f7<br>
	 * C type : TThostFtdcSequenceNoType
	 */
	@Field(32)
	public CThostFtdcQuoteField SequenceNo(int SequenceNo) {
		io.setIntField(this, 32, SequenceNo);
		return this;
	}
	
	/**
	 * \u5356\u65b9\u62a5\u5355\u7f16\u53f7<br>
	 * C type : TThostFtdcOrderSysIDType
	 */
	@Array({ 21 })
	@Field(33)
	public Pointer<Byte> AskOrderSysID() {
		return io.getPointerField(this, 33);
	}
	
	/**
	 * \u4e70\u65b9\u62a5\u5355\u7f16\u53f7<br>
	 * C type : TThostFtdcOrderSysIDType
	 */
	@Array({ 21 })
	@Field(34)
	public Pointer<Byte> BidOrderSysID() {
		return io.getPointerField(this, 34);
	}
	
	/**
	 * \u524d\u7f6e\u7f16\u53f7<br>
	 * C type : TThostFtdcFrontIDType
	 */
	@Field(35)
	public int FrontID() {
		return io.getIntField(this, 35);
	}
	
	/**
	 * \u524d\u7f6e\u7f16\u53f7<br>
	 * C type : TThostFtdcFrontIDType
	 */
	@Field(35)
	public CThostFtdcQuoteField FrontID(int FrontID) {
		io.setIntField(this, 35, FrontID);
		return this;
	}
	
	/**
	 * \u4f1a\u8bdd\u7f16\u53f7<br>
	 * C type : TThostFtdcSessionIDType
	 */
	@Field(36)
	public int SessionID() {
		return io.getIntField(this, 36);
	}
	
	/**
	 * \u4f1a\u8bdd\u7f16\u53f7<br>
	 * C type : TThostFtdcSessionIDType
	 */
	@Field(36)
	public CThostFtdcQuoteField SessionID(int SessionID) {
		io.setIntField(this, 36, SessionID);
		return this;
	}
	
	/**
	 * \u7528\u6237\u7aef\u4ea7\u54c1\u4fe1\u606f<br>
	 * C type : TThostFtdcProductInfoType
	 */
	@Array({ 11 })
	@Field(37)
	public Pointer<Byte> UserProductInfo() {
		return io.getPointerField(this, 37);
	}
	
	/**
	 * \u72b6\u6001\u4fe1\u606f<br>
	 * C type : TThostFtdcErrorMsgType
	 */
	@Array({ 81 })
	@Field(38)
	public Pointer<Byte> StatusMsg() {
		return io.getPointerField(this, 38);
	}
	
	/**
	 * \u64cd\u4f5c\u7528\u6237\u4ee3\u7801<br>
	 * C type : TThostFtdcUserIDType
	 */
	@Array({ 16 })
	@Field(39)
	public Pointer<Byte> ActiveUserID() {
		return io.getPointerField(this, 39);
	}
	
	/**
	 * \u7ecf\u7eaa\u516c\u53f8\u62a5\u4ef7\u7f16\u53f7<br>
	 * C type : TThostFtdcSequenceNoType
	 */
	@Field(40)
	public int BrokerQuoteSeq() {
		return io.getIntField(this, 40);
	}
	
	/**
	 * \u7ecf\u7eaa\u516c\u53f8\u62a5\u4ef7\u7f16\u53f7<br>
	 * C type : TThostFtdcSequenceNoType
	 */
	@Field(40)
	public CThostFtdcQuoteField BrokerQuoteSeq(int BrokerQuoteSeq) {
		io.setIntField(this, 40, BrokerQuoteSeq);
		return this;
	}
	
	/**
	 * \u884d\u751f\u5356\u62a5\u5355\u5f15\u7528<br>
	 * C type : TThostFtdcOrderRefType
	 */
	@Array({ 13 })
	@Field(41)
	public Pointer<Byte> AskOrderRef() {
		return io.getPointerField(this, 41);
	}
	
	/**
	 * \u884d\u751f\u4e70\u62a5\u5355\u5f15\u7528<br>
	 * C type : TThostFtdcOrderRefType
	 */
	@Array({ 13 })
	@Field(42)
	public Pointer<Byte> BidOrderRef() {
		return io.getPointerField(this, 42);
	}
	
	/**
	 * \u5e94\u4ef7\u7f16\u53f7<br>
	 * C type : TThostFtdcOrderSysIDType
	 */
	@Array({ 21 })
	@Field(43)
	public Pointer<Byte> ForQuoteSysID() {
		return io.getPointerField(this, 43);
	}
	
	public CThostFtdcQuoteField() {
		super();
	}
	
	public CThostFtdcQuoteField(Pointer<? extends CPPObject> pointer) {
		super(pointer);
	}
}
