package com.huatai.common.ctp;

import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import org.bridj.ann.Name;
import org.bridj.cpp.CPPObject;

/**
 * \u8f93\u5165\u7684\u7533\u8bf7\u7ec4\u5408<br>
 * <i>native declaration : line 9995</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Name("CThostFtdcInputCombActionField")
@Library("thosttraderapi")
public class CThostFtdcInputCombActionField extends StructObject {
	static {
		BridJ.register();
	}
	
	/**
	 * \u7ecf\u7eaa\u516c\u53f8\u4ee3\u7801<br>
	 * C type : TThostFtdcBrokerIDType
	 */
	@Array({ 11 })
	@Field(0)
	public Pointer<Byte> BrokerID() {
		return io.getPointerField(this, 0);
	}
	
	/**
	 * \u6295\u8d44\u8005\u4ee3\u7801<br>
	 * C type : TThostFtdcInvestorIDType
	 */
	@Array({ 13 })
	@Field(1)
	public Pointer<Byte> InvestorID() {
		return io.getPointerField(this, 1);
	}
	
	/**
	 * \u5408\u7ea6\u4ee3\u7801<br>
	 * C type : TThostFtdcInstrumentIDType
	 */
	@Array({ 31 })
	@Field(2)
	public Pointer<Byte> InstrumentID() {
		return io.getPointerField(this, 2);
	}
	
	/**
	 * \u7ec4\u5408\u5f15\u7528<br>
	 * C type : TThostFtdcOrderRefType
	 */
	@Array({ 13 })
	@Field(3)
	public Pointer<Byte> CombActionRef() {
		return io.getPointerField(this, 3);
	}
	
	/**
	 * \u7528\u6237\u4ee3\u7801<br>
	 * C type : TThostFtdcUserIDType
	 */
	@Array({ 16 })
	@Field(4)
	public Pointer<Byte> UserID() {
		return io.getPointerField(this, 4);
	}
	
	/**
	 * \u4e70\u5356\u65b9\u5411<br>
	 * C type : TThostFtdcDirectionType
	 */
	@Field(5)
	public byte Direction() {
		return io.getByteField(this, 5);
	}
	
	/**
	 * \u4e70\u5356\u65b9\u5411<br>
	 * C type : TThostFtdcDirectionType
	 */
	@Field(5)
	public CThostFtdcInputCombActionField Direction(byte Direction) {
		io.setByteField(this, 5, Direction);
		return this;
	}
	
	/**
	 * \u6570\u91cf<br>
	 * C type : TThostFtdcVolumeType
	 */
	@Field(6)
	public int Volume() {
		return io.getIntField(this, 6);
	}
	
	/**
	 * \u6570\u91cf<br>
	 * C type : TThostFtdcVolumeType
	 */
	@Field(6)
	public CThostFtdcInputCombActionField Volume(int Volume) {
		io.setIntField(this, 6, Volume);
		return this;
	}
	
	/**
	 * \u7ec4\u5408\u6307\u4ee4\u65b9\u5411<br>
	 * C type : TThostFtdcCombDirectionType
	 */
	@Field(7)
	public byte CombDirection() {
		return io.getByteField(this, 7);
	}
	
	/**
	 * \u7ec4\u5408\u6307\u4ee4\u65b9\u5411<br>
	 * C type : TThostFtdcCombDirectionType
	 */
	@Field(7)
	public CThostFtdcInputCombActionField CombDirection(byte CombDirection) {
		io.setByteField(this, 7, CombDirection);
		return this;
	}
	
	/**
	 * \u6295\u673a\u5957\u4fdd\u6807\u5fd7<br>
	 * C type : TThostFtdcHedgeFlagType
	 */
	@Field(8)
	public byte HedgeFlag() {
		return io.getByteField(this, 8);
	}
	
	/**
	 * \u6295\u673a\u5957\u4fdd\u6807\u5fd7<br>
	 * C type : TThostFtdcHedgeFlagType
	 */
	@Field(8)
	public CThostFtdcInputCombActionField HedgeFlag(byte HedgeFlag) {
		io.setByteField(this, 8, HedgeFlag);
		return this;
	}
	
	public CThostFtdcInputCombActionField() {
		super();
	}
	
	public CThostFtdcInputCombActionField(Pointer<? extends CPPObject> pointer) {
		super(pointer);
	}
}
