package com.huatai.common.ctp;

import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import org.bridj.ann.Name;
import org.bridj.cpp.CPPObject;

/**
 * \u8f93\u5165\u7684\u62a5\u4ef7<br>
 * <i>native declaration : line 9545</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Name("CThostFtdcInputQuoteField")
@Library("thosttraderapi")
public class CThostFtdcInputQuoteField extends StructObject {
	static {
		BridJ.register();
	}
	
	/**
	 * \u7ecf\u7eaa\u516c\u53f8\u4ee3\u7801<br>
	 * C type : TThostFtdcBrokerIDType
	 */
	@Array({ 11 })
	@Field(0)
	public Pointer<Byte> BrokerID() {
		return io.getPointerField(this, 0);
	}
	
	/**
	 * \u6295\u8d44\u8005\u4ee3\u7801<br>
	 * C type : TThostFtdcInvestorIDType
	 */
	@Array({ 13 })
	@Field(1)
	public Pointer<Byte> InvestorID() {
		return io.getPointerField(this, 1);
	}
	
	/**
	 * \u5408\u7ea6\u4ee3\u7801<br>
	 * C type : TThostFtdcInstrumentIDType
	 */
	@Array({ 31 })
	@Field(2)
	public Pointer<Byte> InstrumentID() {
		return io.getPointerField(this, 2);
	}
	
	/**
	 * \u62a5\u4ef7\u5f15\u7528<br>
	 * C type : TThostFtdcOrderRefType
	 */
	@Array({ 13 })
	@Field(3)
	public Pointer<Byte> QuoteRef() {
		return io.getPointerField(this, 3);
	}
	
	/**
	 * \u7528\u6237\u4ee3\u7801<br>
	 * C type : TThostFtdcUserIDType
	 */
	@Array({ 16 })
	@Field(4)
	public Pointer<Byte> UserID() {
		return io.getPointerField(this, 4);
	}
	
	/**
	 * \u5356\u4ef7\u683c<br>
	 * C type : TThostFtdcPriceType
	 */
	@Field(5)
	public double AskPrice() {
		return io.getDoubleField(this, 5);
	}
	
	/**
	 * \u5356\u4ef7\u683c<br>
	 * C type : TThostFtdcPriceType
	 */
	@Field(5)
	public CThostFtdcInputQuoteField AskPrice(double AskPrice) {
		io.setDoubleField(this, 5, AskPrice);
		return this;
	}
	
	/**
	 * \u4e70\u4ef7\u683c<br>
	 * C type : TThostFtdcPriceType
	 */
	@Field(6)
	public double BidPrice() {
		return io.getDoubleField(this, 6);
	}
	
	/**
	 * \u4e70\u4ef7\u683c<br>
	 * C type : TThostFtdcPriceType
	 */
	@Field(6)
	public CThostFtdcInputQuoteField BidPrice(double BidPrice) {
		io.setDoubleField(this, 6, BidPrice);
		return this;
	}
	
	/**
	 * \u5356\u6570\u91cf<br>
	 * C type : TThostFtdcVolumeType
	 */
	@Field(7)
	public int AskVolume() {
		return io.getIntField(this, 7);
	}
	
	/**
	 * \u5356\u6570\u91cf<br>
	 * C type : TThostFtdcVolumeType
	 */
	@Field(7)
	public CThostFtdcInputQuoteField AskVolume(int AskVolume) {
		io.setIntField(this, 7, AskVolume);
		return this;
	}
	
	/**
	 * \u4e70\u6570\u91cf<br>
	 * C type : TThostFtdcVolumeType
	 */
	@Field(8)
	public int BidVolume() {
		return io.getIntField(this, 8);
	}
	
	/**
	 * \u4e70\u6570\u91cf<br>
	 * C type : TThostFtdcVolumeType
	 */
	@Field(8)
	public CThostFtdcInputQuoteField BidVolume(int BidVolume) {
		io.setIntField(this, 8, BidVolume);
		return this;
	}
	
	/**
	 * \u8bf7\u6c42\u7f16\u53f7<br>
	 * C type : TThostFtdcRequestIDType
	 */
	@Field(9)
	public int RequestID() {
		return io.getIntField(this, 9);
	}
	
	/**
	 * \u8bf7\u6c42\u7f16\u53f7<br>
	 * C type : TThostFtdcRequestIDType
	 */
	@Field(9)
	public CThostFtdcInputQuoteField RequestID(int RequestID) {
		io.setIntField(this, 9, RequestID);
		return this;
	}
	
	/**
	 * \u4e1a\u52a1\u5355\u5143<br>
	 * C type : TThostFtdcBusinessUnitType
	 */
	@Array({ 21 })
	@Field(10)
	public Pointer<Byte> BusinessUnit() {
		return io.getPointerField(this, 10);
	}
	
	/**
	 * \u5356\u5f00\u5e73\u6807\u5fd7<br>
	 * C type : TThostFtdcOffsetFlagType
	 */
	@Field(11)
	public byte AskOffsetFlag() {
		return io.getByteField(this, 11);
	}
	
	/**
	 * \u5356\u5f00\u5e73\u6807\u5fd7<br>
	 * C type : TThostFtdcOffsetFlagType
	 */
	@Field(11)
	public CThostFtdcInputQuoteField AskOffsetFlag(byte AskOffsetFlag) {
		io.setByteField(this, 11, AskOffsetFlag);
		return this;
	}
	
	/**
	 * \u4e70\u5f00\u5e73\u6807\u5fd7<br>
	 * C type : TThostFtdcOffsetFlagType
	 */
	@Field(12)
	public byte BidOffsetFlag() {
		return io.getByteField(this, 12);
	}
	
	/**
	 * \u4e70\u5f00\u5e73\u6807\u5fd7<br>
	 * C type : TThostFtdcOffsetFlagType
	 */
	@Field(12)
	public CThostFtdcInputQuoteField BidOffsetFlag(byte BidOffsetFlag) {
		io.setByteField(this, 12, BidOffsetFlag);
		return this;
	}
	
	/**
	 * \u5356\u6295\u673a\u5957\u4fdd\u6807\u5fd7<br>
	 * C type : TThostFtdcHedgeFlagType
	 */
	@Field(13)
	public byte AskHedgeFlag() {
		return io.getByteField(this, 13);
	}
	
	/**
	 * \u5356\u6295\u673a\u5957\u4fdd\u6807\u5fd7<br>
	 * C type : TThostFtdcHedgeFlagType
	 */
	@Field(13)
	public CThostFtdcInputQuoteField AskHedgeFlag(byte AskHedgeFlag) {
		io.setByteField(this, 13, AskHedgeFlag);
		return this;
	}
	
	/**
	 * \u4e70\u6295\u673a\u5957\u4fdd\u6807\u5fd7<br>
	 * C type : TThostFtdcHedgeFlagType
	 */
	@Field(14)
	public byte BidHedgeFlag() {
		return io.getByteField(this, 14);
	}
	
	/**
	 * \u4e70\u6295\u673a\u5957\u4fdd\u6807\u5fd7<br>
	 * C type : TThostFtdcHedgeFlagType
	 */
	@Field(14)
	public CThostFtdcInputQuoteField BidHedgeFlag(byte BidHedgeFlag) {
		io.setByteField(this, 14, BidHedgeFlag);
		return this;
	}
	
	/**
	 * \u884d\u751f\u5356\u62a5\u5355\u5f15\u7528<br>
	 * C type : TThostFtdcOrderRefType
	 */
	@Array({ 13 })
	@Field(15)
	public Pointer<Byte> AskOrderRef() {
		return io.getPointerField(this, 15);
	}
	
	/**
	 * \u884d\u751f\u4e70\u62a5\u5355\u5f15\u7528<br>
	 * C type : TThostFtdcOrderRefType
	 */
	@Array({ 13 })
	@Field(16)
	public Pointer<Byte> BidOrderRef() {
		return io.getPointerField(this, 16);
	}
	
	/**
	 * \u5e94\u4ef7\u7f16\u53f7<br>
	 * C type : TThostFtdcOrderSysIDType
	 */
	@Array({ 21 })
	@Field(17)
	public Pointer<Byte> ForQuoteSysID() {
		return io.getPointerField(this, 17);
	}
	
	public CThostFtdcInputQuoteField() {
		super();
	}
	
	public CThostFtdcInputQuoteField(Pointer<? extends CPPObject> pointer) {
		super(pointer);
	}
}
