package com.huatai.common.ctp;

import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import org.bridj.ann.Name;
import org.bridj.cpp.CPPObject;

/**
 * \u6839\u636e\u4ef7\u683c\u67e5\u8be2\u6700\u5927\u62a5\u5355\u6570\u91cf<br>
 * <i>native declaration : line 11408</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Name("CThostFtdcQueryMaxOrderVolumeWithPriceField")
@Library("thosttraderapi")
public class CThostFtdcQueryMaxOrderVolumeWithPriceField extends StructObject {
	static {
		BridJ.register();
	}
	
	/**
	 * \u7ecf\u7eaa\u516c\u53f8\u4ee3\u7801<br>
	 * C type : TThostFtdcBrokerIDType
	 */
	@Array({ 11 })
	@Field(0)
	public Pointer<Byte> BrokerID() {
		return io.getPointerField(this, 0);
	}
	
	/**
	 * \u6295\u8d44\u8005\u4ee3\u7801<br>
	 * C type : TThostFtdcInvestorIDType
	 */
	@Array({ 13 })
	@Field(1)
	public Pointer<Byte> InvestorID() {
		return io.getPointerField(this, 1);
	}
	
	/**
	 * \u5408\u7ea6\u4ee3\u7801<br>
	 * C type : TThostFtdcInstrumentIDType
	 */
	@Array({ 31 })
	@Field(2)
	public Pointer<Byte> InstrumentID() {
		return io.getPointerField(this, 2);
	}
	
	/**
	 * \u4e70\u5356\u65b9\u5411<br>
	 * C type : TThostFtdcDirectionType
	 */
	@Field(3)
	public byte Direction() {
		return io.getByteField(this, 3);
	}
	
	/**
	 * \u4e70\u5356\u65b9\u5411<br>
	 * C type : TThostFtdcDirectionType
	 */
	@Field(3)
	public CThostFtdcQueryMaxOrderVolumeWithPriceField Direction(byte Direction) {
		io.setByteField(this, 3, Direction);
		return this;
	}
	
	/**
	 * \u5f00\u5e73\u6807\u5fd7<br>
	 * C type : TThostFtdcOffsetFlagType
	 */
	@Field(4)
	public byte OffsetFlag() {
		return io.getByteField(this, 4);
	}
	
	/**
	 * \u5f00\u5e73\u6807\u5fd7<br>
	 * C type : TThostFtdcOffsetFlagType
	 */
	@Field(4)
	public CThostFtdcQueryMaxOrderVolumeWithPriceField OffsetFlag(byte OffsetFlag) {
		io.setByteField(this, 4, OffsetFlag);
		return this;
	}
	
	/**
	 * \u6295\u673a\u5957\u4fdd\u6807\u5fd7<br>
	 * C type : TThostFtdcHedgeFlagType
	 */
	@Field(5)
	public byte HedgeFlag() {
		return io.getByteField(this, 5);
	}
	
	/**
	 * \u6295\u673a\u5957\u4fdd\u6807\u5fd7<br>
	 * C type : TThostFtdcHedgeFlagType
	 */
	@Field(5)
	public CThostFtdcQueryMaxOrderVolumeWithPriceField HedgeFlag(byte HedgeFlag) {
		io.setByteField(this, 5, HedgeFlag);
		return this;
	}
	
	/**
	 * \u6700\u5927\u5141\u8bb8\u62a5\u5355\u6570\u91cf<br>
	 * C type : TThostFtdcVolumeType
	 */
	@Field(6)
	public int MaxVolume() {
		return io.getIntField(this, 6);
	}
	
	/**
	 * \u6700\u5927\u5141\u8bb8\u62a5\u5355\u6570\u91cf<br>
	 * C type : TThostFtdcVolumeType
	 */
	@Field(6)
	public CThostFtdcQueryMaxOrderVolumeWithPriceField MaxVolume(int MaxVolume) {
		io.setIntField(this, 6, MaxVolume);
		return this;
	}
	
	/**
	 * \u62a5\u5355\u4ef7\u683c<br>
	 * C type : TThostFtdcPriceType
	 */
	@Field(7)
	public double Price() {
		return io.getDoubleField(this, 7);
	}
	
	/**
	 * \u62a5\u5355\u4ef7\u683c<br>
	 * C type : TThostFtdcPriceType
	 */
	@Field(7)
	public CThostFtdcQueryMaxOrderVolumeWithPriceField Price(double Price) {
		io.setDoubleField(this, 7, Price);
		return this;
	}
	
	public CThostFtdcQueryMaxOrderVolumeWithPriceField() {
		super();
	}
	
	public CThostFtdcQueryMaxOrderVolumeWithPriceField(Pointer<? extends CPPObject> pointer) {
		super(pointer);
	}
}
