package com.huatai.common.ctp;

import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import org.bridj.ann.Name;
import org.bridj.cpp.CPPObject;

/**
 * \u7528\u6237\u53e3\u4ee4\u53d8\u66f4<br>
 * <i>native declaration : line 7484</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Name("CThostFtdcUserPasswordUpdateField")
@Library("thosttraderapi")
public class CThostFtdcUserPasswordUpdateField extends StructObject {
	static {
		BridJ.register();
	}
	
	/**
	 * \u7ecf\u7eaa\u516c\u53f8\u4ee3\u7801<br>
	 * C type : TThostFtdcBrokerIDType
	 */
	@Array({ 11 })
	@Field(0)
	public Pointer<Byte> BrokerID() {
		return io.getPointerField(this, 0);
	}
	
	/**
	 * \u7528\u6237\u4ee3\u7801<br>
	 * C type : TThostFtdcUserIDType
	 */
	@Array({ 16 })
	@Field(1)
	public Pointer<Byte> UserID() {
		return io.getPointerField(this, 1);
	}
	
	/**
	 * \u539f\u6765\u7684\u53e3\u4ee4<br>
	 * C type : TThostFtdcPasswordType
	 */
	@Array({ 41 })
	@Field(2)
	public Pointer<Byte> OldPassword() {
		return io.getPointerField(this, 2);
	}
	
	/**
	 * \u65b0\u7684\u53e3\u4ee4<br>
	 * C type : TThostFtdcPasswordType
	 */
	@Array({ 41 })
	@Field(3)
	public Pointer<Byte> NewPassword() {
		return io.getPointerField(this, 3);
	}
	
	public CThostFtdcUserPasswordUpdateField() {
		super();
	}
	
	public CThostFtdcUserPasswordUpdateField(Pointer<? extends CPPObject> pointer) {
		super(pointer);
	}
}
