package com.huatai.common.ctp;

import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import org.bridj.ann.Name;
import org.bridj.cpp.CPPObject;

/**
 * \u53d8\u66f4\u94f6\u884c\u8d26\u6237\u8bf7\u6c42<br>
 * <i>native declaration : line 11989</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Name("CThostFtdcReqChangeAccountField")
@Library("thosttraderapi")
public class CThostFtdcReqChangeAccountField extends StructObject {
	static {
		BridJ.register();
	}
	
	/**
	 * \u4e1a\u52a1\u529f\u80fd\u7801<br>
	 * C type : TThostFtdcTradeCodeType
	 */
	@Array({ 7 })
	@Field(0)
	public Pointer<Byte> TradeCode() {
		return io.getPointerField(this, 0);
	}
	
	/**
	 * \u94f6\u884c\u4ee3\u7801<br>
	 * C type : TThostFtdcBankIDType
	 */
	@Array({ 4 })
	@Field(1)
	public Pointer<Byte> BankID() {
		return io.getPointerField(this, 1);
	}
	
	/**
	 * \u94f6\u884c\u5206\u652f\u673a\u6784\u4ee3\u7801<br>
	 * C type : TThostFtdcBankBrchIDType
	 */
	@Array({ 5 })
	@Field(2)
	public Pointer<Byte> BankBranchID() {
		return io.getPointerField(this, 2);
	}
	
	/**
	 * \u671f\u5546\u4ee3\u7801<br>
	 * C type : TThostFtdcBrokerIDType
	 */
	@Array({ 11 })
	@Field(3)
	public Pointer<Byte> BrokerID() {
		return io.getPointerField(this, 3);
	}
	
	/**
	 * \u671f\u5546\u5206\u652f\u673a\u6784\u4ee3\u7801<br>
	 * C type : TThostFtdcFutureBranchIDType
	 */
	@Array({ 31 })
	@Field(4)
	public Pointer<Byte> BrokerBranchID() {
		return io.getPointerField(this, 4);
	}
	
	/**
	 * \u4ea4\u6613\u65e5\u671f<br>
	 * C type : TThostFtdcTradeDateType
	 */
	@Array({ 9 })
	@Field(5)
	public Pointer<Byte> TradeDate() {
		return io.getPointerField(this, 5);
	}
	
	/**
	 * \u4ea4\u6613\u65f6\u95f4<br>
	 * C type : TThostFtdcTradeTimeType
	 */
	@Array({ 9 })
	@Field(6)
	public Pointer<Byte> TradeTime() {
		return io.getPointerField(this, 6);
	}
	
	/**
	 * \u94f6\u884c\u6d41\u6c34\u53f7<br>
	 * C type : TThostFtdcBankSerialType
	 */
	@Array({ 13 })
	@Field(7)
	public Pointer<Byte> BankSerial() {
		return io.getPointerField(this, 7);
	}
	
	/**
	 * \u4ea4\u6613\u7cfb\u7edf\u65e5\u671f<br>
	 * C type : TThostFtdcTradeDateType
	 */
	@Array({ 9 })
	@Field(8)
	public Pointer<Byte> TradingDay() {
		return io.getPointerField(this, 8);
	}
	
	/**
	 * \u94f6\u671f\u5e73\u53f0\u6d88\u606f\u6d41\u6c34\u53f7<br>
	 * C type : TThostFtdcSerialType
	 */
	@Field(9)
	public int PlateSerial() {
		return io.getIntField(this, 9);
	}
	
	/**
	 * \u94f6\u671f\u5e73\u53f0\u6d88\u606f\u6d41\u6c34\u53f7<br>
	 * C type : TThostFtdcSerialType
	 */
	@Field(9)
	public CThostFtdcReqChangeAccountField PlateSerial(int PlateSerial) {
		io.setIntField(this, 9, PlateSerial);
		return this;
	}
	
	/**
	 * \u6700\u540e\u5206\u7247\u6807\u5fd7<br>
	 * C type : TThostFtdcLastFragmentType
	 */
	@Field(10)
	public byte LastFragment() {
		return io.getByteField(this, 10);
	}
	
	/**
	 * \u6700\u540e\u5206\u7247\u6807\u5fd7<br>
	 * C type : TThostFtdcLastFragmentType
	 */
	@Field(10)
	public CThostFtdcReqChangeAccountField LastFragment(byte LastFragment) {
		io.setByteField(this, 10, LastFragment);
		return this;
	}
	
	/**
	 * \u4f1a\u8bdd\u53f7<br>
	 * C type : TThostFtdcSessionIDType
	 */
	@Field(11)
	public int SessionID() {
		return io.getIntField(this, 11);
	}
	
	/**
	 * \u4f1a\u8bdd\u53f7<br>
	 * C type : TThostFtdcSessionIDType
	 */
	@Field(11)
	public CThostFtdcReqChangeAccountField SessionID(int SessionID) {
		io.setIntField(this, 11, SessionID);
		return this;
	}
	
	/**
	 * \u5ba2\u6237\u59d3\u540d<br>
	 * C type : TThostFtdcIndividualNameType
	 */
	@Array({ 51 })
	@Field(12)
	public Pointer<Byte> CustomerName() {
		return io.getPointerField(this, 12);
	}
	
	/**
	 * \u8bc1\u4ef6\u7c7b\u578b<br>
	 * C type : TThostFtdcIdCardTypeType
	 */
	@Field(13)
	public byte IdCardType() {
		return io.getByteField(this, 13);
	}
	
	/**
	 * \u8bc1\u4ef6\u7c7b\u578b<br>
	 * C type : TThostFtdcIdCardTypeType
	 */
	@Field(13)
	public CThostFtdcReqChangeAccountField IdCardType(byte IdCardType) {
		io.setByteField(this, 13, IdCardType);
		return this;
	}
	
	/**
	 * \u8bc1\u4ef6\u53f7\u7801<br>
	 * C type : TThostFtdcIdentifiedCardNoType
	 */
	@Array({ 51 })
	@Field(14)
	public Pointer<Byte> IdentifiedCardNo() {
		return io.getPointerField(this, 14);
	}
	
	/**
	 * \u6027\u522b<br>
	 * C type : TThostFtdcGenderType
	 */
	@Field(15)
	public byte Gender() {
		return io.getByteField(this, 15);
	}
	
	/**
	 * \u6027\u522b<br>
	 * C type : TThostFtdcGenderType
	 */
	@Field(15)
	public CThostFtdcReqChangeAccountField Gender(byte Gender) {
		io.setByteField(this, 15, Gender);
		return this;
	}
	
	/**
	 * \u56fd\u5bb6\u4ee3\u7801<br>
	 * C type : TThostFtdcCountryCodeType
	 */
	@Array({ 21 })
	@Field(16)
	public Pointer<Byte> CountryCode() {
		return io.getPointerField(this, 16);
	}
	
	/**
	 * \u5ba2\u6237\u7c7b\u578b<br>
	 * C type : TThostFtdcCustTypeType
	 */
	@Field(17)
	public byte CustType() {
		return io.getByteField(this, 17);
	}
	
	/**
	 * \u5ba2\u6237\u7c7b\u578b<br>
	 * C type : TThostFtdcCustTypeType
	 */
	@Field(17)
	public CThostFtdcReqChangeAccountField CustType(byte CustType) {
		io.setByteField(this, 17, CustType);
		return this;
	}
	
	/**
	 * \u5730\u5740<br>
	 * C type : TThostFtdcAddressType
	 */
	@Array({ 101 })
	@Field(18)
	public Pointer<Byte> Address() {
		return io.getPointerField(this, 18);
	}
	
	/**
	 * \u90ae\u7f16<br>
	 * C type : TThostFtdcZipCodeType
	 */
	@Array({ 7 })
	@Field(19)
	public Pointer<Byte> ZipCode() {
		return io.getPointerField(this, 19);
	}
	
	/**
	 * \u7535\u8bdd\u53f7\u7801<br>
	 * C type : TThostFtdcTelephoneType
	 */
	@Array({ 41 })
	@Field(20)
	public Pointer<Byte> Telephone() {
		return io.getPointerField(this, 20);
	}
	
	/**
	 * \u624b\u673a<br>
	 * C type : TThostFtdcMobilePhoneType
	 */
	@Array({ 21 })
	@Field(21)
	public Pointer<Byte> MobilePhone() {
		return io.getPointerField(this, 21);
	}
	
	/**
	 * \u4f20\u771f<br>
	 * C type : TThostFtdcFaxType
	 */
	@Array({ 41 })
	@Field(22)
	public Pointer<Byte> Fax() {
		return io.getPointerField(this, 22);
	}
	
	/**
	 * \u7535\u5b50\u90ae\u4ef6<br>
	 * C type : TThostFtdcEMailType
	 */
	@Array({ 41 })
	@Field(23)
	public Pointer<Byte> EMail() {
		return io.getPointerField(this, 23);
	}
	
	/**
	 * \u8d44\u91d1\u8d26\u6237\u72b6\u6001<br>
	 * C type : TThostFtdcMoneyAccountStatusType
	 */
	@Field(24)
	public byte MoneyAccountStatus() {
		return io.getByteField(this, 24);
	}
	
	/**
	 * \u8d44\u91d1\u8d26\u6237\u72b6\u6001<br>
	 * C type : TThostFtdcMoneyAccountStatusType
	 */
	@Field(24)
	public CThostFtdcReqChangeAccountField MoneyAccountStatus(byte MoneyAccountStatus) {
		io.setByteField(this, 24, MoneyAccountStatus);
		return this;
	}
	
	/**
	 * \u94f6\u884c\u5e10\u53f7<br>
	 * C type : TThostFtdcBankAccountType
	 */
	@Array({ 41 })
	@Field(25)
	public Pointer<Byte> BankAccount() {
		return io.getPointerField(this, 25);
	}
	
	/**
	 * \u94f6\u884c\u5bc6\u7801<br>
	 * C type : TThostFtdcPasswordType
	 */
	@Array({ 41 })
	@Field(26)
	public Pointer<Byte> BankPassWord() {
		return io.getPointerField(this, 26);
	}
	
	/**
	 * \u65b0\u94f6\u884c\u5e10\u53f7<br>
	 * C type : TThostFtdcBankAccountType
	 */
	@Array({ 41 })
	@Field(27)
	public Pointer<Byte> NewBankAccount() {
		return io.getPointerField(this, 27);
	}
	
	/**
	 * \u65b0\u94f6\u884c\u5bc6\u7801<br>
	 * C type : TThostFtdcPasswordType
	 */
	@Array({ 41 })
	@Field(28)
	public Pointer<Byte> NewBankPassWord() {
		return io.getPointerField(this, 28);
	}
	
	/**
	 * \u6295\u8d44\u8005\u5e10\u53f7<br>
	 * C type : TThostFtdcAccountIDType
	 */
	@Array({ 13 })
	@Field(29)
	public Pointer<Byte> AccountID() {
		return io.getPointerField(this, 29);
	}
	
	/**
	 * \u671f\u8d27\u5bc6\u7801<br>
	 * C type : TThostFtdcPasswordType
	 */
	@Array({ 41 })
	@Field(30)
	public Pointer<Byte> Password() {
		return io.getPointerField(this, 30);
	}
	
	/**
	 * \u94f6\u884c\u5e10\u53f7\u7c7b\u578b<br>
	 * C type : TThostFtdcBankAccTypeType
	 */
	@Field(31)
	public byte BankAccType() {
		return io.getByteField(this, 31);
	}
	
	/**
	 * \u94f6\u884c\u5e10\u53f7\u7c7b\u578b<br>
	 * C type : TThostFtdcBankAccTypeType
	 */
	@Field(31)
	public CThostFtdcReqChangeAccountField BankAccType(byte BankAccType) {
		io.setByteField(this, 31, BankAccType);
		return this;
	}
	
	/**
	 * \u5b89\u88c5\u7f16\u53f7<br>
	 * C type : TThostFtdcInstallIDType
	 */
	@Field(32)
	public int InstallID() {
		return io.getIntField(this, 32);
	}
	
	/**
	 * \u5b89\u88c5\u7f16\u53f7<br>
	 * C type : TThostFtdcInstallIDType
	 */
	@Field(32)
	public CThostFtdcReqChangeAccountField InstallID(int InstallID) {
		io.setIntField(this, 32, InstallID);
		return this;
	}
	
	/**
	 * \u9a8c\u8bc1\u5ba2\u6237\u8bc1\u4ef6\u53f7\u7801\u6807\u5fd7<br>
	 * C type : TThostFtdcYesNoIndicatorType
	 */
	@Field(33)
	public byte VerifyCertNoFlag() {
		return io.getByteField(this, 33);
	}
	
	/**
	 * \u9a8c\u8bc1\u5ba2\u6237\u8bc1\u4ef6\u53f7\u7801\u6807\u5fd7<br>
	 * C type : TThostFtdcYesNoIndicatorType
	 */
	@Field(33)
	public CThostFtdcReqChangeAccountField VerifyCertNoFlag(byte VerifyCertNoFlag) {
		io.setByteField(this, 33, VerifyCertNoFlag);
		return this;
	}
	
	/**
	 * \u5e01\u79cd\u4ee3\u7801<br>
	 * C type : TThostFtdcCurrencyIDType
	 */
	@Array({ 4 })
	@Field(34)
	public Pointer<Byte> CurrencyID() {
		return io.getPointerField(this, 34);
	}
	
	/**
	 * \u671f\u8d27\u516c\u53f8\u94f6\u884c\u7f16\u7801<br>
	 * C type : TThostFtdcBankCodingForFutureType
	 */
	@Array({ 33 })
	@Field(35)
	public Pointer<Byte> BrokerIDByBank() {
		return io.getPointerField(this, 35);
	}
	
	/**
	 * \u94f6\u884c\u5bc6\u7801\u6807\u5fd7<br>
	 * C type : TThostFtdcPwdFlagType
	 */
	@Field(36)
	public byte BankPwdFlag() {
		return io.getByteField(this, 36);
	}
	
	/**
	 * \u94f6\u884c\u5bc6\u7801\u6807\u5fd7<br>
	 * C type : TThostFtdcPwdFlagType
	 */
	@Field(36)
	public CThostFtdcReqChangeAccountField BankPwdFlag(byte BankPwdFlag) {
		io.setByteField(this, 36, BankPwdFlag);
		return this;
	}
	
	/**
	 * \u671f\u8d27\u8d44\u91d1\u5bc6\u7801\u6838\u5bf9\u6807\u5fd7<br>
	 * C type : TThostFtdcPwdFlagType
	 */
	@Field(37)
	public byte SecuPwdFlag() {
		return io.getByteField(this, 37);
	}
	
	/**
	 * \u671f\u8d27\u8d44\u91d1\u5bc6\u7801\u6838\u5bf9\u6807\u5fd7<br>
	 * C type : TThostFtdcPwdFlagType
	 */
	@Field(37)
	public CThostFtdcReqChangeAccountField SecuPwdFlag(byte SecuPwdFlag) {
		io.setByteField(this, 37, SecuPwdFlag);
		return this;
	}
	
	/**
	 * \u4ea4\u6613ID<br>
	 * C type : TThostFtdcTIDType
	 */
	@Field(38)
	public int TID() {
		return io.getIntField(this, 38);
	}
	
	/**
	 * \u4ea4\u6613ID<br>
	 * C type : TThostFtdcTIDType
	 */
	@Field(38)
	public CThostFtdcReqChangeAccountField TID(int TID) {
		io.setIntField(this, 38, TID);
		return this;
	}
	
	/**
	 * \u6458\u8981<br>
	 * C type : TThostFtdcDigestType
	 */
	@Array({ 36 })
	@Field(39)
	public Pointer<Byte> Digest() {
		return io.getPointerField(this, 39);
	}
	
	public CThostFtdcReqChangeAccountField() {
		super();
	}
	
	public CThostFtdcReqChangeAccountField(Pointer<? extends CPPObject> pointer) {
		super(pointer);
	}
}
