package com.huatai.common.ctp;

import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import org.bridj.ann.Name;
import org.bridj.cpp.CPPObject;

/**
 * \u4ea4\u6613\u6240\u8be2\u4ef7\u4fe1\u606f<br>
 * <i>native declaration : line 9505</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Name("CThostFtdcExchangeForQuoteField")
@Library("thosttraderapi")
public class CThostFtdcExchangeForQuoteField extends StructObject {
	static {
		BridJ.register();
	}
	
	/**
	 * \u672c\u5730\u8be2\u4ef7\u7f16\u53f7<br>
	 * C type : TThostFtdcOrderLocalIDType
	 */
	@Array({ 13 })
	@Field(0)
	public Pointer<Byte> ForQuoteLocalID() {
		return io.getPointerField(this, 0);
	}
	
	/**
	 * \u4ea4\u6613\u6240\u4ee3\u7801<br>
	 * C type : TThostFtdcExchangeIDType
	 */
	@Array({ 9 })
	@Field(1)
	public Pointer<Byte> ExchangeID() {
		return io.getPointerField(this, 1);
	}
	
	/**
	 * \u4f1a\u5458\u4ee3\u7801<br>
	 * C type : TThostFtdcParticipantIDType
	 */
	@Array({ 11 })
	@Field(2)
	public Pointer<Byte> ParticipantID() {
		return io.getPointerField(this, 2);
	}
	
	/**
	 * \u5ba2\u6237\u4ee3\u7801<br>
	 * C type : TThostFtdcClientIDType
	 */
	@Array({ 11 })
	@Field(3)
	public Pointer<Byte> ClientID() {
		return io.getPointerField(this, 3);
	}
	
	/**
	 * \u5408\u7ea6\u5728\u4ea4\u6613\u6240\u7684\u4ee3\u7801<br>
	 * C type : TThostFtdcExchangeInstIDType
	 */
	@Array({ 31 })
	@Field(4)
	public Pointer<Byte> ExchangeInstID() {
		return io.getPointerField(this, 4);
	}
	
	/**
	 * \u4ea4\u6613\u6240\u4ea4\u6613\u5458\u4ee3\u7801<br>
	 * C type : TThostFtdcTraderIDType
	 */
	@Array({ 21 })
	@Field(5)
	public Pointer<Byte> TraderID() {
		return io.getPointerField(this, 5);
	}
	
	/**
	 * \u5b89\u88c5\u7f16\u53f7<br>
	 * C type : TThostFtdcInstallIDType
	 */
	@Field(6)
	public int InstallID() {
		return io.getIntField(this, 6);
	}
	
	/**
	 * \u5b89\u88c5\u7f16\u53f7<br>
	 * C type : TThostFtdcInstallIDType
	 */
	@Field(6)
	public CThostFtdcExchangeForQuoteField InstallID(int InstallID) {
		io.setIntField(this, 6, InstallID);
		return this;
	}
	
	/**
	 * \u62a5\u5355\u65e5\u671f<br>
	 * C type : TThostFtdcDateType
	 */
	@Array({ 9 })
	@Field(7)
	public Pointer<Byte> InsertDate() {
		return io.getPointerField(this, 7);
	}
	
	/**
	 * \u63d2\u5165\u65f6\u95f4<br>
	 * C type : TThostFtdcTimeType
	 */
	@Array({ 9 })
	@Field(8)
	public Pointer<Byte> InsertTime() {
		return io.getPointerField(this, 8);
	}
	
	/**
	 * \u8be2\u4ef7\u72b6\u6001<br>
	 * C type : TThostFtdcForQuoteStatusType
	 */
	@Field(9)
	public byte ForQuoteStatus() {
		return io.getByteField(this, 9);
	}
	
	/**
	 * \u8be2\u4ef7\u72b6\u6001<br>
	 * C type : TThostFtdcForQuoteStatusType
	 */
	@Field(9)
	public CThostFtdcExchangeForQuoteField ForQuoteStatus(byte ForQuoteStatus) {
		io.setByteField(this, 9, ForQuoteStatus);
		return this;
	}
	
	public CThostFtdcExchangeForQuoteField() {
		super();
	}
	
	public CThostFtdcExchangeForQuoteField(Pointer<? extends CPPObject> pointer) {
		super(pointer);
	}
}
