package com.huatai.common.ctp;

import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import org.bridj.ann.Name;
import org.bridj.cpp.CPPObject;

/**
 * \u671f\u6743\u5408\u7ea6delta\u503c<br>
 * <i>native declaration : line 9917</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Name("CThostFtdcOptionInstrDeltaField")
@Library("thosttraderapi")
public class CThostFtdcOptionInstrDeltaField extends StructObject {
	static {
		BridJ.register();
	}
	
	/**
	 * \u5408\u7ea6\u4ee3\u7801<br>
	 * C type : TThostFtdcInstrumentIDType
	 */
	@Array({ 31 })
	@Field(0)
	public Pointer<Byte> InstrumentID() {
		return io.getPointerField(this, 0);
	}
	
	/**
	 * \u6295\u8d44\u8005\u8303\u56f4<br>
	 * C type : TThostFtdcInvestorRangeType
	 */
	@Field(1)
	public byte InvestorRange() {
		return io.getByteField(this, 1);
	}
	
	/**
	 * \u6295\u8d44\u8005\u8303\u56f4<br>
	 * C type : TThostFtdcInvestorRangeType
	 */
	@Field(1)
	public CThostFtdcOptionInstrDeltaField InvestorRange(byte InvestorRange) {
		io.setByteField(this, 1, InvestorRange);
		return this;
	}
	
	/**
	 * \u7ecf\u7eaa\u516c\u53f8\u4ee3\u7801<br>
	 * C type : TThostFtdcBrokerIDType
	 */
	@Array({ 11 })
	@Field(2)
	public Pointer<Byte> BrokerID() {
		return io.getPointerField(this, 2);
	}
	
	/**
	 * \u6295\u8d44\u8005\u4ee3\u7801<br>
	 * C type : TThostFtdcInvestorIDType
	 */
	@Array({ 13 })
	@Field(3)
	public Pointer<Byte> InvestorID() {
		return io.getPointerField(this, 3);
	}
	
	/**
	 * Delta\u503c<br>
	 * C type : TThostFtdcRatioType
	 */
	@Field(4)
	public double Delta() {
		return io.getDoubleField(this, 4);
	}
	
	/**
	 * Delta\u503c<br>
	 * C type : TThostFtdcRatioType
	 */
	@Field(4)
	public CThostFtdcOptionInstrDeltaField Delta(double Delta) {
		io.setDoubleField(this, 4, Delta);
		return this;
	}
	
	public CThostFtdcOptionInstrDeltaField() {
		super();
	}
	
	public CThostFtdcOptionInstrDeltaField(Pointer<? extends CPPObject> pointer) {
		super(pointer);
	}
}
