package com.huatai.common.ctp;

import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import org.bridj.ann.Name;
import org.bridj.cpp.CPPObject;

/**
 * \u7528\u6237\u4f1a\u8bdd<br>
 * <i>native declaration : line 8035</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Name("CThostFtdcUserSessionField")
@Library("thosttraderapi")
public class CThostFtdcUserSessionField extends StructObject {
	static {
		BridJ.register();
	}
	
	/**
	 * \u524d\u7f6e\u7f16\u53f7<br>
	 * C type : TThostFtdcFrontIDType
	 */
	@Field(0)
	public int FrontID() {
		return io.getIntField(this, 0);
	}
	
	/**
	 * \u524d\u7f6e\u7f16\u53f7<br>
	 * C type : TThostFtdcFrontIDType
	 */
	@Field(0)
	public CThostFtdcUserSessionField FrontID(int FrontID) {
		io.setIntField(this, 0, FrontID);
		return this;
	}
	
	/**
	 * \u4f1a\u8bdd\u7f16\u53f7<br>
	 * C type : TThostFtdcSessionIDType
	 */
	@Field(1)
	public int SessionID() {
		return io.getIntField(this, 1);
	}
	
	/**
	 * \u4f1a\u8bdd\u7f16\u53f7<br>
	 * C type : TThostFtdcSessionIDType
	 */
	@Field(1)
	public CThostFtdcUserSessionField SessionID(int SessionID) {
		io.setIntField(this, 1, SessionID);
		return this;
	}
	
	/**
	 * \u7ecf\u7eaa\u516c\u53f8\u4ee3\u7801<br>
	 * C type : TThostFtdcBrokerIDType
	 */
	@Array({ 11 })
	@Field(2)
	public Pointer<Byte> BrokerID() {
		return io.getPointerField(this, 2);
	}
	
	/**
	 * \u7528\u6237\u4ee3\u7801<br>
	 * C type : TThostFtdcUserIDType
	 */
	@Array({ 16 })
	@Field(3)
	public Pointer<Byte> UserID() {
		return io.getPointerField(this, 3);
	}
	
	/**
	 * \u767b\u5f55\u65e5\u671f<br>
	 * C type : TThostFtdcDateType
	 */
	@Array({ 9 })
	@Field(4)
	public Pointer<Byte> LoginDate() {
		return io.getPointerField(this, 4);
	}
	
	/**
	 * \u767b\u5f55\u65f6\u95f4<br>
	 * C type : TThostFtdcTimeType
	 */
	@Array({ 9 })
	@Field(5)
	public Pointer<Byte> LoginTime() {
		return io.getPointerField(this, 5);
	}
	
	/**
	 * IP\u5730\u5740<br>
	 * C type : TThostFtdcIPAddressType
	 */
	@Array({ 16 })
	@Field(6)
	public Pointer<Byte> IPAddress() {
		return io.getPointerField(this, 6);
	}
	
	/**
	 * \u7528\u6237\u7aef\u4ea7\u54c1\u4fe1\u606f<br>
	 * C type : TThostFtdcProductInfoType
	 */
	@Array({ 11 })
	@Field(7)
	public Pointer<Byte> UserProductInfo() {
		return io.getPointerField(this, 7);
	}
	
	/**
	 * \u63a5\u53e3\u7aef\u4ea7\u54c1\u4fe1\u606f<br>
	 * C type : TThostFtdcProductInfoType
	 */
	@Array({ 11 })
	@Field(8)
	public Pointer<Byte> InterfaceProductInfo() {
		return io.getPointerField(this, 8);
	}
	
	/**
	 * \u534f\u8bae\u4fe1\u606f<br>
	 * C type : TThostFtdcProtocolInfoType
	 */
	@Array({ 11 })
	@Field(9)
	public Pointer<Byte> ProtocolInfo() {
		return io.getPointerField(this, 9);
	}
	
	/**
	 * Mac\u5730\u5740<br>
	 * C type : TThostFtdcMacAddressType
	 */
	@Array({ 21 })
	@Field(10)
	public Pointer<Byte> MacAddress() {
		return io.getPointerField(this, 10);
	}
	
	public CThostFtdcUserSessionField() {
		super();
	}
	
	public CThostFtdcUserSessionField(Pointer<? extends CPPObject> pointer) {
		super(pointer);
	}
}
