package com.huatai.common.ctp;

import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import org.bridj.ann.Name;
import org.bridj.cpp.CPPObject;

/**
 * \u7ec4\u5408\u4ea4\u6613\u5408\u7ea6\u7684\u5355\u817f<br>
 * <i>native declaration : line 10706</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Name("CThostFtdcCombinationLegField")
@Library("thosttraderapi")
public class CThostFtdcCombinationLegField extends StructObject {
	static {
		BridJ.register();
	}
	
	/**
	 * \u7ec4\u5408\u5408\u7ea6\u4ee3\u7801<br>
	 * C type : TThostFtdcInstrumentIDType
	 */
	@Array({ 31 })
	@Field(0)
	public Pointer<Byte> CombInstrumentID() {
		return io.getPointerField(this, 0);
	}
	
	/**
	 * \u5355\u817f\u7f16\u53f7<br>
	 * C type : TThostFtdcLegIDType
	 */
	@Field(1)
	public int LegID() {
		return io.getIntField(this, 1);
	}
	
	/**
	 * \u5355\u817f\u7f16\u53f7<br>
	 * C type : TThostFtdcLegIDType
	 */
	@Field(1)
	public CThostFtdcCombinationLegField LegID(int LegID) {
		io.setIntField(this, 1, LegID);
		return this;
	}
	
	/**
	 * \u5355\u817f\u5408\u7ea6\u4ee3\u7801<br>
	 * C type : TThostFtdcInstrumentIDType
	 */
	@Array({ 31 })
	@Field(2)
	public Pointer<Byte> LegInstrumentID() {
		return io.getPointerField(this, 2);
	}
	
	/**
	 * \u4e70\u5356\u65b9\u5411<br>
	 * C type : TThostFtdcDirectionType
	 */
	@Field(3)
	public byte Direction() {
		return io.getByteField(this, 3);
	}
	
	/**
	 * \u4e70\u5356\u65b9\u5411<br>
	 * C type : TThostFtdcDirectionType
	 */
	@Field(3)
	public CThostFtdcCombinationLegField Direction(byte Direction) {
		io.setByteField(this, 3, Direction);
		return this;
	}
	
	/**
	 * \u5355\u817f\u4e58\u6570<br>
	 * C type : TThostFtdcLegMultipleType
	 */
	@Field(4)
	public int LegMultiple() {
		return io.getIntField(this, 4);
	}
	
	/**
	 * \u5355\u817f\u4e58\u6570<br>
	 * C type : TThostFtdcLegMultipleType
	 */
	@Field(4)
	public CThostFtdcCombinationLegField LegMultiple(int LegMultiple) {
		io.setIntField(this, 4, LegMultiple);
		return this;
	}
	
	/**
	 * \u6d3e\u751f\u5c42\u6570<br>
	 * C type : TThostFtdcImplyLevelType
	 */
	@Field(5)
	public int ImplyLevel() {
		return io.getIntField(this, 5);
	}
	
	/**
	 * \u6d3e\u751f\u5c42\u6570<br>
	 * C type : TThostFtdcImplyLevelType
	 */
	@Field(5)
	public CThostFtdcCombinationLegField ImplyLevel(int ImplyLevel) {
		io.setIntField(this, 5, ImplyLevel);
		return this;
	}
	
	public CThostFtdcCombinationLegField() {
		super();
	}
	
	public CThostFtdcCombinationLegField(Pointer<? extends CPPObject> pointer) {
		super(pointer);
	}
}
