package com.huatai.common.ctp;

import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import org.bridj.ann.Name;
import org.bridj.cpp.CPPObject;

/**
 * \u901a\u8baf\u9636\u6bb5<br>
 * <i>native declaration : line 7402</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Name("CThostFtdcCommPhaseField")
@Library("thosttraderapi")
public class CThostFtdcCommPhaseField extends StructObject {
	static {
		BridJ.register();
	}
	
	/**
	 * \u4ea4\u6613\u65e5<br>
	 * C type : TThostFtdcDateType
	 */
	@Array({ 9 })
	@Field(0)
	public Pointer<Byte> TradingDay() {
		return io.getPointerField(this, 0);
	}
	
	/**
	 * \u901a\u8baf\u65f6\u6bb5\u7f16\u53f7<br>
	 * C type : TThostFtdcCommPhaseNoType
	 */
	@Field(1)
	public short CommPhaseNo() {
		return io.getShortField(this, 1);
	}
	
	/**
	 * \u901a\u8baf\u65f6\u6bb5\u7f16\u53f7<br>
	 * C type : TThostFtdcCommPhaseNoType
	 */
	@Field(1)
	public CThostFtdcCommPhaseField CommPhaseNo(short CommPhaseNo) {
		io.setShortField(this, 1, CommPhaseNo);
		return this;
	}
	
	/**
	 * \u7cfb\u7edf\u7f16\u53f7<br>
	 * C type : TThostFtdcSystemIDType
	 */
	@Array({ 21 })
	@Field(2)
	public Pointer<Byte> SystemID() {
		return io.getPointerField(this, 2);
	}
	
	public CThostFtdcCommPhaseField() {
		super();
	}
	
	public CThostFtdcCommPhaseField(Pointer<? extends CPPObject> pointer) {
		super(pointer);
	}
}
