package com.huatai.common.ctp;

import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import org.bridj.ann.Name;
import org.bridj.cpp.CPPObject;

/**
 * \u5f53\u524d\u671f\u6743\u5408\u7ea6\u4fdd\u8bc1\u91d1\u8c03\u6574\u7cfb\u6570<br>
 * <i>native declaration : line 8844</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Name("CThostFtdcOptionInstrMarginAdjustField")
@Library("thosttraderapi")
public class CThostFtdcOptionInstrMarginAdjustField extends StructObject {
	static {
		BridJ.register();
	}
	
	/**
	 * \u5408\u7ea6\u4ee3\u7801<br>
	 * C type : TThostFtdcInstrumentIDType
	 */
	@Array({ 31 })
	@Field(0)
	public Pointer<Byte> InstrumentID() {
		return io.getPointerField(this, 0);
	}
	
	/**
	 * \u6295\u8d44\u8005\u8303\u56f4<br>
	 * C type : TThostFtdcInvestorRangeType
	 */
	@Field(1)
	public byte InvestorRange() {
		return io.getByteField(this, 1);
	}
	
	/**
	 * \u6295\u8d44\u8005\u8303\u56f4<br>
	 * C type : TThostFtdcInvestorRangeType
	 */
	@Field(1)
	public CThostFtdcOptionInstrMarginAdjustField InvestorRange(byte InvestorRange) {
		io.setByteField(this, 1, InvestorRange);
		return this;
	}
	
	/**
	 * \u7ecf\u7eaa\u516c\u53f8\u4ee3\u7801<br>
	 * C type : TThostFtdcBrokerIDType
	 */
	@Array({ 11 })
	@Field(2)
	public Pointer<Byte> BrokerID() {
		return io.getPointerField(this, 2);
	}
	
	/**
	 * \u6295\u8d44\u8005\u4ee3\u7801<br>
	 * C type : TThostFtdcInvestorIDType
	 */
	@Array({ 13 })
	@Field(3)
	public Pointer<Byte> InvestorID() {
		return io.getPointerField(this, 3);
	}
	
	/**
	 * \u6295\u673a\u7a7a\u5934\u4fdd\u8bc1\u91d1\u8c03\u6574\u7cfb\u6570<br>
	 * C type : TThostFtdcRatioType
	 */
	@Field(4)
	public double SShortMarginRatioByMoney() {
		return io.getDoubleField(this, 4);
	}
	
	/**
	 * \u6295\u673a\u7a7a\u5934\u4fdd\u8bc1\u91d1\u8c03\u6574\u7cfb\u6570<br>
	 * C type : TThostFtdcRatioType
	 */
	@Field(4)
	public CThostFtdcOptionInstrMarginAdjustField SShortMarginRatioByMoney(double SShortMarginRatioByMoney) {
		io.setDoubleField(this, 4, SShortMarginRatioByMoney);
		return this;
	}
	
	/**
	 * \u6295\u673a\u7a7a\u5934\u4fdd\u8bc1\u91d1\u8c03\u6574\u7cfb\u6570<br>
	 * C type : TThostFtdcMoneyType
	 */
	@Field(5)
	public double SShortMarginRatioByVolume() {
		return io.getDoubleField(this, 5);
	}
	
	/**
	 * \u6295\u673a\u7a7a\u5934\u4fdd\u8bc1\u91d1\u8c03\u6574\u7cfb\u6570<br>
	 * C type : TThostFtdcMoneyType
	 */
	@Field(5)
	public CThostFtdcOptionInstrMarginAdjustField SShortMarginRatioByVolume(double SShortMarginRatioByVolume) {
		io.setDoubleField(this, 5, SShortMarginRatioByVolume);
		return this;
	}
	
	/**
	 * \u4fdd\u503c\u7a7a\u5934\u4fdd\u8bc1\u91d1\u8c03\u6574\u7cfb\u6570<br>
	 * C type : TThostFtdcRatioType
	 */
	@Field(6)
	public double HShortMarginRatioByMoney() {
		return io.getDoubleField(this, 6);
	}
	
	/**
	 * \u4fdd\u503c\u7a7a\u5934\u4fdd\u8bc1\u91d1\u8c03\u6574\u7cfb\u6570<br>
	 * C type : TThostFtdcRatioType
	 */
	@Field(6)
	public CThostFtdcOptionInstrMarginAdjustField HShortMarginRatioByMoney(double HShortMarginRatioByMoney) {
		io.setDoubleField(this, 6, HShortMarginRatioByMoney);
		return this;
	}
	
	/**
	 * \u4fdd\u503c\u7a7a\u5934\u4fdd\u8bc1\u91d1\u8c03\u6574\u7cfb\u6570<br>
	 * C type : TThostFtdcMoneyType
	 */
	@Field(7)
	public double HShortMarginRatioByVolume() {
		return io.getDoubleField(this, 7);
	}
	
	/**
	 * \u4fdd\u503c\u7a7a\u5934\u4fdd\u8bc1\u91d1\u8c03\u6574\u7cfb\u6570<br>
	 * C type : TThostFtdcMoneyType
	 */
	@Field(7)
	public CThostFtdcOptionInstrMarginAdjustField HShortMarginRatioByVolume(double HShortMarginRatioByVolume) {
		io.setDoubleField(this, 7, HShortMarginRatioByVolume);
		return this;
	}
	
	/**
	 * \u5957\u5229\u7a7a\u5934\u4fdd\u8bc1\u91d1\u8c03\u6574\u7cfb\u6570<br>
	 * C type : TThostFtdcRatioType
	 */
	@Field(8)
	public double AShortMarginRatioByMoney() {
		return io.getDoubleField(this, 8);
	}
	
	/**
	 * \u5957\u5229\u7a7a\u5934\u4fdd\u8bc1\u91d1\u8c03\u6574\u7cfb\u6570<br>
	 * C type : TThostFtdcRatioType
	 */
	@Field(8)
	public CThostFtdcOptionInstrMarginAdjustField AShortMarginRatioByMoney(double AShortMarginRatioByMoney) {
		io.setDoubleField(this, 8, AShortMarginRatioByMoney);
		return this;
	}
	
	/**
	 * \u5957\u5229\u7a7a\u5934\u4fdd\u8bc1\u91d1\u8c03\u6574\u7cfb\u6570<br>
	 * C type : TThostFtdcMoneyType
	 */
	@Field(9)
	public double AShortMarginRatioByVolume() {
		return io.getDoubleField(this, 9);
	}
	
	/**
	 * \u5957\u5229\u7a7a\u5934\u4fdd\u8bc1\u91d1\u8c03\u6574\u7cfb\u6570<br>
	 * C type : TThostFtdcMoneyType
	 */
	@Field(9)
	public CThostFtdcOptionInstrMarginAdjustField AShortMarginRatioByVolume(double AShortMarginRatioByVolume) {
		io.setDoubleField(this, 9, AShortMarginRatioByVolume);
		return this;
	}
	
	/**
	 * \u662f\u5426\u8ddf\u968f\u4ea4\u6613\u6240\u6536\u53d6<br>
	 * C type : TThostFtdcBoolType
	 */
	@Field(10)
	public int IsRelative() {
		return io.getIntField(this, 10);
	}
	
	/**
	 * \u662f\u5426\u8ddf\u968f\u4ea4\u6613\u6240\u6536\u53d6<br>
	 * C type : TThostFtdcBoolType
	 */
	@Field(10)
	public CThostFtdcOptionInstrMarginAdjustField IsRelative(int IsRelative) {
		io.setIntField(this, 10, IsRelative);
		return this;
	}
	
	public CThostFtdcOptionInstrMarginAdjustField() {
		super();
	}
	
	public CThostFtdcOptionInstrMarginAdjustField(Pointer<? extends CPPObject> pointer) {
		super(pointer);
	}
}
