package com.huatai.common.ctp;

import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import org.bridj.ann.Name;
import org.bridj.cpp.CPPObject;

/**
 * \u6295\u8d44\u8005\u7ec4<br>
 * <i>native declaration : line 6830</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Name("CThostFtdcInvestorGroupField")
@Library("thosttraderapi")
public class CThostFtdcInvestorGroupField extends StructObject {
	static {
		BridJ.register();
	}
	
	/**
	 * \u7ecf\u7eaa\u516c\u53f8\u4ee3\u7801<br>
	 * C type : TThostFtdcBrokerIDType
	 */
	@Array({ 11 })
	@Field(0)
	public Pointer<Byte> BrokerID() {
		return io.getPointerField(this, 0);
	}
	
	/**
	 * \u6295\u8d44\u8005\u5206\u7ec4\u4ee3\u7801<br>
	 * C type : TThostFtdcInvestorIDType
	 */
	@Array({ 13 })
	@Field(1)
	public Pointer<Byte> InvestorGroupID() {
		return io.getPointerField(this, 1);
	}
	
	/**
	 * \u6295\u8d44\u8005\u5206\u7ec4\u540d\u79f0<br>
	 * C type : TThostFtdcInvestorGroupNameType
	 */
	@Array({ 41 })
	@Field(2)
	public Pointer<Byte> InvestorGroupName() {
		return io.getPointerField(this, 2);
	}
	
	public CThostFtdcInvestorGroupField() {
		super();
	}
	
	public CThostFtdcInvestorGroupField(Pointer<? extends CPPObject> pointer) {
		super(pointer);
	}
}
