package com.huatai.common.ctp;

import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import org.bridj.ann.Name;
import org.bridj.cpp.CPPObject;

/**
 * \u7ecf\u7eaa\u516c\u53f8\u4ea4\u6613\u53c2\u6570<br>
 * <i>native declaration : line 11440</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Name("CThostFtdcBrokerTradingParamsField")
@Library("thosttraderapi")
public class CThostFtdcBrokerTradingParamsField extends StructObject {
	static {
		BridJ.register();
	}
	
	/**
	 * \u7ecf\u7eaa\u516c\u53f8\u4ee3\u7801<br>
	 * C type : TThostFtdcBrokerIDType
	 */
	@Array({ 11 })
	@Field(0)
	public Pointer<Byte> BrokerID() {
		return io.getPointerField(this, 0);
	}
	
	/**
	 * \u6295\u8d44\u8005\u4ee3\u7801<br>
	 * C type : TThostFtdcInvestorIDType
	 */
	@Array({ 13 })
	@Field(1)
	public Pointer<Byte> InvestorID() {
		return io.getPointerField(this, 1);
	}
	
	/**
	 * \u4fdd\u8bc1\u91d1\u4ef7\u683c\u7c7b\u578b<br>
	 * C type : TThostFtdcMarginPriceTypeType
	 */
	@Field(2)
	public byte MarginPriceType() {
		return io.getByteField(this, 2);
	}
	
	/**
	 * \u4fdd\u8bc1\u91d1\u4ef7\u683c\u7c7b\u578b<br>
	 * C type : TThostFtdcMarginPriceTypeType
	 */
	@Field(2)
	public CThostFtdcBrokerTradingParamsField MarginPriceType(byte MarginPriceType) {
		io.setByteField(this, 2, MarginPriceType);
		return this;
	}
	
	/**
	 * \u76c8\u4e8f\u7b97\u6cd5<br>
	 * C type : TThostFtdcAlgorithmType
	 */
	@Field(3)
	public byte Algorithm() {
		return io.getByteField(this, 3);
	}
	
	/**
	 * \u76c8\u4e8f\u7b97\u6cd5<br>
	 * C type : TThostFtdcAlgorithmType
	 */
	@Field(3)
	public CThostFtdcBrokerTradingParamsField Algorithm(byte Algorithm) {
		io.setByteField(this, 3, Algorithm);
		return this;
	}
	
	/**
	 * \u53ef\u7528\u662f\u5426\u5305\u542b\u5e73\u4ed3\u76c8\u5229<br>
	 * C type : TThostFtdcIncludeCloseProfitType
	 */
	@Field(4)
	public byte AvailIncludeCloseProfit() {
		return io.getByteField(this, 4);
	}
	
	/**
	 * \u53ef\u7528\u662f\u5426\u5305\u542b\u5e73\u4ed3\u76c8\u5229<br>
	 * C type : TThostFtdcIncludeCloseProfitType
	 */
	@Field(4)
	public CThostFtdcBrokerTradingParamsField AvailIncludeCloseProfit(byte AvailIncludeCloseProfit) {
		io.setByteField(this, 4, AvailIncludeCloseProfit);
		return this;
	}
	
	/**
	 * \u5e01\u79cd\u4ee3\u7801<br>
	 * C type : TThostFtdcCurrencyIDType
	 */
	@Array({ 4 })
	@Field(5)
	public Pointer<Byte> CurrencyID() {
		return io.getPointerField(this, 5);
	}
	
	/**
	 * \u671f\u6743\u6743\u5229\u91d1\u4ef7\u683c\u7c7b\u578b<br>
	 * C type : TThostFtdcOptionRoyaltyPriceTypeType
	 */
	@Field(6)
	public byte OptionRoyaltyPriceType() {
		return io.getByteField(this, 6);
	}
	
	/**
	 * \u671f\u6743\u6743\u5229\u91d1\u4ef7\u683c\u7c7b\u578b<br>
	 * C type : TThostFtdcOptionRoyaltyPriceTypeType
	 */
	@Field(6)
	public CThostFtdcBrokerTradingParamsField OptionRoyaltyPriceType(byte OptionRoyaltyPriceType) {
		io.setByteField(this, 6, OptionRoyaltyPriceType);
		return this;
	}
	
	public CThostFtdcBrokerTradingParamsField() {
		super();
	}
	
	public CThostFtdcBrokerTradingParamsField(Pointer<? extends CPPObject> pointer) {
		super(pointer);
	}
}
