package com.huatai.common.ctp;

import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import org.bridj.ann.Name;
import org.bridj.cpp.CPPObject;

/**
 * \u54cd\u5e94\u4fe1\u606f<br>
 * <i>native declaration : line 6591</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Name("CThostFtdcRspInfoField")
@Library("thosttraderapi")
public class CThostFtdcRspInfoField extends StructObject {
	static {
		BridJ.register();
	}
	
	/**
	 * \u9519\u8bef\u4ee3\u7801<br>
	 * C type : TThostFtdcErrorIDType
	 */
	@Field(0)
	public int ErrorID() {
		return io.getIntField(this, 0);
	}
	
	/**
	 * \u9519\u8bef\u4ee3\u7801<br>
	 * C type : TThostFtdcErrorIDType
	 */
	@Field(0)
	public CThostFtdcRspInfoField ErrorID(int ErrorID) {
		io.setIntField(this, 0, ErrorID);
		return this;
	}
	
	/**
	 * \u9519\u8bef\u4fe1\u606f<br>
	 * C type : TThostFtdcErrorMsgType
	 */
	@Array({ 81 })
	@Field(1)
	public Pointer<Byte> ErrorMsg() {
		return io.getPointerField(this, 1);
	}
	
	public CThostFtdcRspInfoField() {
		super();
	}
	
	public CThostFtdcRspInfoField(Pointer<? extends CPPObject> pointer) {
		super(pointer);
	}
}
