package com.huatai.common.ctp;

import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import org.bridj.ann.Name;
import org.bridj.cpp.CPPObject;

/**
 * \u6b63\u5728\u540c\u6b65\u4e2d\u7684\u5408\u7ea6\u4fdd\u8bc1\u91d1\u7387<br>
 * <i>native declaration : line 8382</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Name("CThostFtdcSyncingInstrumentMarginRateField")
@Library("thosttraderapi")
public class CThostFtdcSyncingInstrumentMarginRateField extends StructObject {
	static {
		BridJ.register();
	}
	
	/**
	 * \u5408\u7ea6\u4ee3\u7801<br>
	 * C type : TThostFtdcInstrumentIDType
	 */
	@Array({ 31 })
	@Field(0)
	public Pointer<Byte> InstrumentID() {
		return io.getPointerField(this, 0);
	}
	
	/**
	 * \u6295\u8d44\u8005\u8303\u56f4<br>
	 * C type : TThostFtdcInvestorRangeType
	 */
	@Field(1)
	public byte InvestorRange() {
		return io.getByteField(this, 1);
	}
	
	/**
	 * \u6295\u8d44\u8005\u8303\u56f4<br>
	 * C type : TThostFtdcInvestorRangeType
	 */
	@Field(1)
	public CThostFtdcSyncingInstrumentMarginRateField InvestorRange(byte InvestorRange) {
		io.setByteField(this, 1, InvestorRange);
		return this;
	}
	
	/**
	 * \u7ecf\u7eaa\u516c\u53f8\u4ee3\u7801<br>
	 * C type : TThostFtdcBrokerIDType
	 */
	@Array({ 11 })
	@Field(2)
	public Pointer<Byte> BrokerID() {
		return io.getPointerField(this, 2);
	}
	
	/**
	 * \u6295\u8d44\u8005\u4ee3\u7801<br>
	 * C type : TThostFtdcInvestorIDType
	 */
	@Array({ 13 })
	@Field(3)
	public Pointer<Byte> InvestorID() {
		return io.getPointerField(this, 3);
	}
	
	/**
	 * \u6295\u673a\u5957\u4fdd\u6807\u5fd7<br>
	 * C type : TThostFtdcHedgeFlagType
	 */
	@Field(4)
	public byte HedgeFlag() {
		return io.getByteField(this, 4);
	}
	
	/**
	 * \u6295\u673a\u5957\u4fdd\u6807\u5fd7<br>
	 * C type : TThostFtdcHedgeFlagType
	 */
	@Field(4)
	public CThostFtdcSyncingInstrumentMarginRateField HedgeFlag(byte HedgeFlag) {
		io.setByteField(this, 4, HedgeFlag);
		return this;
	}
	
	/**
	 * \u591a\u5934\u4fdd\u8bc1\u91d1\u7387<br>
	 * C type : TThostFtdcRatioType
	 */
	@Field(5)
	public double LongMarginRatioByMoney() {
		return io.getDoubleField(this, 5);
	}
	
	/**
	 * \u591a\u5934\u4fdd\u8bc1\u91d1\u7387<br>
	 * C type : TThostFtdcRatioType
	 */
	@Field(5)
	public CThostFtdcSyncingInstrumentMarginRateField LongMarginRatioByMoney(double LongMarginRatioByMoney) {
		io.setDoubleField(this, 5, LongMarginRatioByMoney);
		return this;
	}
	
	/**
	 * \u591a\u5934\u4fdd\u8bc1\u91d1\u8d39<br>
	 * C type : TThostFtdcMoneyType
	 */
	@Field(6)
	public double LongMarginRatioByVolume() {
		return io.getDoubleField(this, 6);
	}
	
	/**
	 * \u591a\u5934\u4fdd\u8bc1\u91d1\u8d39<br>
	 * C type : TThostFtdcMoneyType
	 */
	@Field(6)
	public CThostFtdcSyncingInstrumentMarginRateField LongMarginRatioByVolume(double LongMarginRatioByVolume) {
		io.setDoubleField(this, 6, LongMarginRatioByVolume);
		return this;
	}
	
	/**
	 * \u7a7a\u5934\u4fdd\u8bc1\u91d1\u7387<br>
	 * C type : TThostFtdcRatioType
	 */
	@Field(7)
	public double ShortMarginRatioByMoney() {
		return io.getDoubleField(this, 7);
	}
	
	/**
	 * \u7a7a\u5934\u4fdd\u8bc1\u91d1\u7387<br>
	 * C type : TThostFtdcRatioType
	 */
	@Field(7)
	public CThostFtdcSyncingInstrumentMarginRateField ShortMarginRatioByMoney(double ShortMarginRatioByMoney) {
		io.setDoubleField(this, 7, ShortMarginRatioByMoney);
		return this;
	}
	
	/**
	 * \u7a7a\u5934\u4fdd\u8bc1\u91d1\u8d39<br>
	 * C type : TThostFtdcMoneyType
	 */
	@Field(8)
	public double ShortMarginRatioByVolume() {
		return io.getDoubleField(this, 8);
	}
	
	/**
	 * \u7a7a\u5934\u4fdd\u8bc1\u91d1\u8d39<br>
	 * C type : TThostFtdcMoneyType
	 */
	@Field(8)
	public CThostFtdcSyncingInstrumentMarginRateField ShortMarginRatioByVolume(double ShortMarginRatioByVolume) {
		io.setDoubleField(this, 8, ShortMarginRatioByVolume);
		return this;
	}
	
	/**
	 * \u662f\u5426\u76f8\u5bf9\u4ea4\u6613\u6240\u6536\u53d6<br>
	 * C type : TThostFtdcBoolType
	 */
	@Field(9)
	public int IsRelative() {
		return io.getIntField(this, 9);
	}
	
	/**
	 * \u662f\u5426\u76f8\u5bf9\u4ea4\u6613\u6240\u6536\u53d6<br>
	 * C type : TThostFtdcBoolType
	 */
	@Field(9)
	public CThostFtdcSyncingInstrumentMarginRateField IsRelative(int IsRelative) {
		io.setIntField(this, 9, IsRelative);
		return this;
	}
	
	public CThostFtdcSyncingInstrumentMarginRateField() {
		super();
	}
	
	public CThostFtdcSyncingInstrumentMarginRateField(Pointer<? extends CPPObject> pointer) {
		super(pointer);
	}
}
