package com.huatai.common.ctp;

import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import org.bridj.ann.Name;
import org.bridj.cpp.CPPObject;

/**
 * \u53d1\u7ed9\u505a\u5e02\u5546\u7684\u8be2\u4ef7\u8bf7\u6c42<br>
 * <i>native declaration : line 9932</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Name("CThostFtdcForQuoteRspField")
@Library("thosttraderapi")
public class CThostFtdcForQuoteRspField extends StructObject {
	static {
		BridJ.register();
	}
	
	/**
	 * \u4ea4\u6613\u65e5<br>
	 * C type : TThostFtdcDateType
	 */
	@Array({ 9 })
	@Field(0)
	public Pointer<Byte> TradingDay() {
		return io.getPointerField(this, 0);
	}
	
	/**
	 * \u5408\u7ea6\u4ee3\u7801<br>
	 * C type : TThostFtdcInstrumentIDType
	 */
	@Array({ 31 })
	@Field(1)
	public Pointer<Byte> InstrumentID() {
		return io.getPointerField(this, 1);
	}
	
	/**
	 * \u8be2\u4ef7\u7f16\u53f7<br>
	 * C type : TThostFtdcOrderSysIDType
	 */
	@Array({ 21 })
	@Field(2)
	public Pointer<Byte> ForQuoteSysID() {
		return io.getPointerField(this, 2);
	}
	
	/**
	 * \u8be2\u4ef7\u65f6\u95f4<br>
	 * C type : TThostFtdcTimeType
	 */
	@Array({ 9 })
	@Field(3)
	public Pointer<Byte> ForQuoteTime() {
		return io.getPointerField(this, 3);
	}
	
	/**
	 * \u4e1a\u52a1\u65e5\u671f<br>
	 * C type : TThostFtdcDateType
	 */
	@Array({ 9 })
	@Field(4)
	public Pointer<Byte> ActionDay() {
		return io.getPointerField(this, 4);
	}
	
	/**
	 * \u4ea4\u6613\u6240\u4ee3\u7801<br>
	 * C type : TThostFtdcExchangeIDType
	 */
	@Array({ 9 })
	@Field(5)
	public Pointer<Byte> ExchangeID() {
		return io.getPointerField(this, 5);
	}
	
	public CThostFtdcForQuoteRspField() {
		super();
	}
	
	public CThostFtdcForQuoteRspField(Pointer<? extends CPPObject> pointer) {
		super(pointer);
	}
}
