package com.huatai.common.ctp;

import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import org.bridj.ann.Name;
import org.bridj.cpp.CPPObject;

/**
 * \u671f\u6743\u4ea4\u6613\u6210\u672c<br>
 * <i>native declaration : line 8900</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Name("CThostFtdcOptionInstrTradeCostField")
@Library("thosttraderapi")
public class CThostFtdcOptionInstrTradeCostField extends StructObject {
	static {
		BridJ.register();
	}
	
	/**
	 * \u7ecf\u7eaa\u516c\u53f8\u4ee3\u7801<br>
	 * C type : TThostFtdcBrokerIDType
	 */
	@Array({ 11 })
	@Field(0)
	public Pointer<Byte> BrokerID() {
		return io.getPointerField(this, 0);
	}
	
	/**
	 * \u6295\u8d44\u8005\u4ee3\u7801<br>
	 * C type : TThostFtdcInvestorIDType
	 */
	@Array({ 13 })
	@Field(1)
	public Pointer<Byte> InvestorID() {
		return io.getPointerField(this, 1);
	}
	
	/**
	 * \u5408\u7ea6\u4ee3\u7801<br>
	 * C type : TThostFtdcInstrumentIDType
	 */
	@Array({ 31 })
	@Field(2)
	public Pointer<Byte> InstrumentID() {
		return io.getPointerField(this, 2);
	}
	
	/**
	 * \u6295\u673a\u5957\u4fdd\u6807\u5fd7<br>
	 * C type : TThostFtdcHedgeFlagType
	 */
	@Field(3)
	public byte HedgeFlag() {
		return io.getByteField(this, 3);
	}
	
	/**
	 * \u6295\u673a\u5957\u4fdd\u6807\u5fd7<br>
	 * C type : TThostFtdcHedgeFlagType
	 */
	@Field(3)
	public CThostFtdcOptionInstrTradeCostField HedgeFlag(byte HedgeFlag) {
		io.setByteField(this, 3, HedgeFlag);
		return this;
	}
	
	/**
	 * \u671f\u6743\u5408\u7ea6\u4fdd\u8bc1\u91d1\u4e0d\u53d8\u90e8\u5206<br>
	 * C type : TThostFtdcMoneyType
	 */
	@Field(4)
	public double FixedMargin() {
		return io.getDoubleField(this, 4);
	}
	
	/**
	 * \u671f\u6743\u5408\u7ea6\u4fdd\u8bc1\u91d1\u4e0d\u53d8\u90e8\u5206<br>
	 * C type : TThostFtdcMoneyType
	 */
	@Field(4)
	public CThostFtdcOptionInstrTradeCostField FixedMargin(double FixedMargin) {
		io.setDoubleField(this, 4, FixedMargin);
		return this;
	}
	
	/**
	 * \u671f\u6743\u5408\u7ea6\u6700\u5c0f\u4fdd\u8bc1\u91d1<br>
	 * C type : TThostFtdcMoneyType
	 */
	@Field(5)
	public double MiniMargin() {
		return io.getDoubleField(this, 5);
	}
	
	/**
	 * \u671f\u6743\u5408\u7ea6\u6700\u5c0f\u4fdd\u8bc1\u91d1<br>
	 * C type : TThostFtdcMoneyType
	 */
	@Field(5)
	public CThostFtdcOptionInstrTradeCostField MiniMargin(double MiniMargin) {
		io.setDoubleField(this, 5, MiniMargin);
		return this;
	}
	
	/**
	 * \u671f\u6743\u5408\u7ea6\u6743\u5229\u91d1<br>
	 * C type : TThostFtdcMoneyType
	 */
	@Field(6)
	public double Royalty() {
		return io.getDoubleField(this, 6);
	}
	
	/**
	 * \u671f\u6743\u5408\u7ea6\u6743\u5229\u91d1<br>
	 * C type : TThostFtdcMoneyType
	 */
	@Field(6)
	public CThostFtdcOptionInstrTradeCostField Royalty(double Royalty) {
		io.setDoubleField(this, 6, Royalty);
		return this;
	}
	
	/**
	 * \u4ea4\u6613\u6240\u671f\u6743\u5408\u7ea6\u4fdd\u8bc1\u91d1\u4e0d\u53d8\u90e8\u5206<br>
	 * C type : TThostFtdcMoneyType
	 */
	@Field(7)
	public double ExchFixedMargin() {
		return io.getDoubleField(this, 7);
	}
	
	/**
	 * \u4ea4\u6613\u6240\u671f\u6743\u5408\u7ea6\u4fdd\u8bc1\u91d1\u4e0d\u53d8\u90e8\u5206<br>
	 * C type : TThostFtdcMoneyType
	 */
	@Field(7)
	public CThostFtdcOptionInstrTradeCostField ExchFixedMargin(double ExchFixedMargin) {
		io.setDoubleField(this, 7, ExchFixedMargin);
		return this;
	}
	
	/**
	 * \u4ea4\u6613\u6240\u671f\u6743\u5408\u7ea6\u6700\u5c0f\u4fdd\u8bc1\u91d1<br>
	 * C type : TThostFtdcMoneyType
	 */
	@Field(8)
	public double ExchMiniMargin() {
		return io.getDoubleField(this, 8);
	}
	
	/**
	 * \u4ea4\u6613\u6240\u671f\u6743\u5408\u7ea6\u6700\u5c0f\u4fdd\u8bc1\u91d1<br>
	 * C type : TThostFtdcMoneyType
	 */
	@Field(8)
	public CThostFtdcOptionInstrTradeCostField ExchMiniMargin(double ExchMiniMargin) {
		io.setDoubleField(this, 8, ExchMiniMargin);
		return this;
	}
	
	public CThostFtdcOptionInstrTradeCostField() {
		super();
	}
	
	public CThostFtdcOptionInstrTradeCostField(Pointer<? extends CPPObject> pointer) {
		super(pointer);
	}
}
