package com.huatai.common.ctp;

import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import org.bridj.ann.Name;
import org.bridj.cpp.CPPObject;

/**
 * \u5408\u7ea6\u72b6\u6001<br>
 * <i>native declaration : line 10360</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Name("CThostFtdcInstrumentStatusField")
@Library("thosttraderapi")
public class CThostFtdcInstrumentStatusField extends StructObject {
	static {
		BridJ.register();
	}
	
	/**
	 * \u4ea4\u6613\u6240\u4ee3\u7801<br>
	 * C type : TThostFtdcExchangeIDType
	 */
	@Array({ 9 })
	@Field(0)
	public Pointer<Byte> ExchangeID() {
		return io.getPointerField(this, 0);
	}
	
	/**
	 * \u5408\u7ea6\u5728\u4ea4\u6613\u6240\u7684\u4ee3\u7801<br>
	 * C type : TThostFtdcExchangeInstIDType
	 */
	@Array({ 31 })
	@Field(1)
	public Pointer<Byte> ExchangeInstID() {
		return io.getPointerField(this, 1);
	}
	
	/**
	 * \u7ed3\u7b97\u7ec4\u4ee3\u7801<br>
	 * C type : TThostFtdcSettlementGroupIDType
	 */
	@Array({ 9 })
	@Field(2)
	public Pointer<Byte> SettlementGroupID() {
		return io.getPointerField(this, 2);
	}
	
	/**
	 * \u5408\u7ea6\u4ee3\u7801<br>
	 * C type : TThostFtdcInstrumentIDType
	 */
	@Array({ 31 })
	@Field(3)
	public Pointer<Byte> InstrumentID() {
		return io.getPointerField(this, 3);
	}
	
	/**
	 * \u5408\u7ea6\u4ea4\u6613\u72b6\u6001<br>
	 * C type : TThostFtdcInstrumentStatusType
	 */
	@Field(4)
	public byte InstrumentStatus() {
		return io.getByteField(this, 4);
	}
	
	/**
	 * \u5408\u7ea6\u4ea4\u6613\u72b6\u6001<br>
	 * C type : TThostFtdcInstrumentStatusType
	 */
	@Field(4)
	public CThostFtdcInstrumentStatusField InstrumentStatus(byte InstrumentStatus) {
		io.setByteField(this, 4, InstrumentStatus);
		return this;
	}
	
	/**
	 * \u4ea4\u6613\u9636\u6bb5\u7f16\u53f7<br>
	 * C type : TThostFtdcTradingSegmentSNType
	 */
	@Field(5)
	public int TradingSegmentSN() {
		return io.getIntField(this, 5);
	}
	
	/**
	 * \u4ea4\u6613\u9636\u6bb5\u7f16\u53f7<br>
	 * C type : TThostFtdcTradingSegmentSNType
	 */
	@Field(5)
	public CThostFtdcInstrumentStatusField TradingSegmentSN(int TradingSegmentSN) {
		io.setIntField(this, 5, TradingSegmentSN);
		return this;
	}
	
	/**
	 * \u8fdb\u5165\u672c\u72b6\u6001\u65f6\u95f4<br>
	 * C type : TThostFtdcTimeType
	 */
	@Array({ 9 })
	@Field(6)
	public Pointer<Byte> EnterTime() {
		return io.getPointerField(this, 6);
	}
	
	/**
	 * \u8fdb\u5165\u672c\u72b6\u6001\u539f\u56e0<br>
	 * C type : TThostFtdcInstStatusEnterReasonType
	 */
	@Field(7)
	public byte EnterReason() {
		return io.getByteField(this, 7);
	}
	
	/**
	 * \u8fdb\u5165\u672c\u72b6\u6001\u539f\u56e0<br>
	 * C type : TThostFtdcInstStatusEnterReasonType
	 */
	@Field(7)
	public CThostFtdcInstrumentStatusField EnterReason(byte EnterReason) {
		io.setByteField(this, 7, EnterReason);
		return this;
	}
	
	public CThostFtdcInstrumentStatusField() {
		super();
	}
	
	public CThostFtdcInstrumentStatusField(Pointer<? extends CPPObject> pointer) {
		super(pointer);
	}
}
