package com.huatai.common.ctp;

import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import org.bridj.ann.Name;
import org.bridj.cpp.CPPObject;

/**
 * \u7528\u6237\u4e8b\u4ef6\u901a\u77e5\u4fe1\u606f<br>
 * <i>native declaration : line 11088</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Name("CThostFtdcTradingNoticeInfoField")
@Library("thosttraderapi")
public class CThostFtdcTradingNoticeInfoField extends StructObject {
	static {
		BridJ.register();
	}
	
	/**
	 * \u7ecf\u7eaa\u516c\u53f8\u4ee3\u7801<br>
	 * C type : TThostFtdcBrokerIDType
	 */
	@Array({ 11 })
	@Field(0)
	public Pointer<Byte> BrokerID() {
		return io.getPointerField(this, 0);
	}
	
	/**
	 * \u6295\u8d44\u8005\u4ee3\u7801<br>
	 * C type : TThostFtdcInvestorIDType
	 */
	@Array({ 13 })
	@Field(1)
	public Pointer<Byte> InvestorID() {
		return io.getPointerField(this, 1);
	}
	
	/**
	 * \u53d1\u9001\u65f6\u95f4<br>
	 * C type : TThostFtdcTimeType
	 */
	@Array({ 9 })
	@Field(2)
	public Pointer<Byte> SendTime() {
		return io.getPointerField(this, 2);
	}
	
	/**
	 * \u6d88\u606f\u6b63\u6587<br>
	 * C type : TThostFtdcContentType
	 */
	@Array({ 501 })
	@Field(3)
	public Pointer<Byte> FieldContent() {
		return io.getPointerField(this, 3);
	}
	
	/**
	 * \u5e8f\u5217\u7cfb\u5217\u53f7<br>
	 * C type : TThostFtdcSequenceSeriesType
	 */
	@Field(4)
	public short SequenceSeries() {
		return io.getShortField(this, 4);
	}
	
	/**
	 * \u5e8f\u5217\u7cfb\u5217\u53f7<br>
	 * C type : TThostFtdcSequenceSeriesType
	 */
	@Field(4)
	public CThostFtdcTradingNoticeInfoField SequenceSeries(short SequenceSeries) {
		io.setShortField(this, 4, SequenceSeries);
		return this;
	}
	
	/**
	 * \u5e8f\u5217\u53f7<br>
	 * C type : TThostFtdcSequenceNoType
	 */
	@Field(5)
	public int SequenceNo() {
		return io.getIntField(this, 5);
	}
	
	/**
	 * \u5e8f\u5217\u53f7<br>
	 * C type : TThostFtdcSequenceNoType
	 */
	@Field(5)
	public CThostFtdcTradingNoticeInfoField SequenceNo(int SequenceNo) {
		io.setIntField(this, 5, SequenceNo);
		return this;
	}
	
	public CThostFtdcTradingNoticeInfoField() {
		super();
	}
	
	public CThostFtdcTradingNoticeInfoField(Pointer<? extends CPPObject> pointer) {
		super(pointer);
	}
}
