package com.huatai.common.ctp;

import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import org.bridj.ann.Name;
import org.bridj.cpp.CPPObject;

/**
 * \u7528\u6237\u767b\u5f55\u5e94\u7b54<br>
 * <i>native declaration : line 6332</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Name("CThostFtdcRspUserLoginField")
@Library("thosttraderapi")
public class CThostFtdcRspUserLoginField extends StructObject {
	static {
		BridJ.register();
	}
	
	/**
	 * \u4ea4\u6613\u65e5<br>
	 * C type : TThostFtdcDateType
	 */
	@Array({ 9 })
	@Field(0)
	public Pointer<Byte> TradingDay() {
		return io.getPointerField(this, 0);
	}
	
	/**
	 * \u767b\u5f55\u6210\u529f\u65f6\u95f4<br>
	 * C type : TThostFtdcTimeType
	 */
	@Array({ 9 })
	@Field(1)
	public Pointer<Byte> LoginTime() {
		return io.getPointerField(this, 1);
	}
	
	/**
	 * \u7ecf\u7eaa\u516c\u53f8\u4ee3\u7801<br>
	 * C type : TThostFtdcBrokerIDType
	 */
	@Array({ 11 })
	@Field(2)
	public Pointer<Byte> BrokerID() {
		return io.getPointerField(this, 2);
	}
	
	/**
	 * \u7528\u6237\u4ee3\u7801<br>
	 * C type : TThostFtdcUserIDType
	 */
	@Array({ 16 })
	@Field(3)
	public Pointer<Byte> UserID() {
		return io.getPointerField(this, 3);
	}
	
	/**
	 * \u4ea4\u6613\u7cfb\u7edf\u540d\u79f0<br>
	 * C type : TThostFtdcSystemNameType
	 */
	@Array({ 41 })
	@Field(4)
	public Pointer<Byte> SystemName() {
		return io.getPointerField(this, 4);
	}
	
	/**
	 * \u524d\u7f6e\u7f16\u53f7<br>
	 * C type : TThostFtdcFrontIDType
	 */
	@Field(5)
	public int FrontID() {
		return io.getIntField(this, 5);
	}
	
	/**
	 * \u524d\u7f6e\u7f16\u53f7<br>
	 * C type : TThostFtdcFrontIDType
	 */
	@Field(5)
	public CThostFtdcRspUserLoginField FrontID(int FrontID) {
		io.setIntField(this, 5, FrontID);
		return this;
	}
	
	/**
	 * \u4f1a\u8bdd\u7f16\u53f7<br>
	 * C type : TThostFtdcSessionIDType
	 */
	@Field(6)
	public int SessionID() {
		return io.getIntField(this, 6);
	}
	
	/**
	 * \u4f1a\u8bdd\u7f16\u53f7<br>
	 * C type : TThostFtdcSessionIDType
	 */
	@Field(6)
	public CThostFtdcRspUserLoginField SessionID(int SessionID) {
		io.setIntField(this, 6, SessionID);
		return this;
	}
	
	/**
	 * \u6700\u5927\u62a5\u5355\u5f15\u7528<br>
	 * C type : TThostFtdcOrderRefType
	 */
	@Array({ 13 })
	@Field(7)
	public Pointer<Byte> MaxOrderRef() {
		return io.getPointerField(this, 7);
	}
	
	/**
	 * \u4e0a\u671f\u6240\u65f6\u95f4<br>
	 * C type : TThostFtdcTimeType
	 */
	@Array({ 9 })
	@Field(8)
	public Pointer<Byte> SHFETime() {
		return io.getPointerField(this, 8);
	}
	
	/**
	 * \u5927\u5546\u6240\u65f6\u95f4<br>
	 * C type : TThostFtdcTimeType
	 */
	@Array({ 9 })
	@Field(9)
	public Pointer<Byte> DCETime() {
		return io.getPointerField(this, 9);
	}
	
	/**
	 * \u90d1\u5546\u6240\u65f6\u95f4<br>
	 * C type : TThostFtdcTimeType
	 */
	@Array({ 9 })
	@Field(10)
	public Pointer<Byte> CZCETime() {
		return io.getPointerField(this, 10);
	}
	
	/**
	 * \u4e2d\u91d1\u6240\u65f6\u95f4<br>
	 * C type : TThostFtdcTimeType
	 */
	@Array({ 9 })
	@Field(11)
	public Pointer<Byte> FFEXTime() {
		return io.getPointerField(this, 11);
	}
	
	/**
	 * \u80fd\u6e90\u4e2d\u5fc3\u65f6\u95f4<br>
	 * C type : TThostFtdcTimeType
	 */
	@Array({ 9 })
	@Field(12)
	public Pointer<Byte> INETime() {
		return io.getPointerField(this, 12);
	}
	
	public CThostFtdcRspUserLoginField() {
		super();
	}
	
	public CThostFtdcRspUserLoginField(Pointer<? extends CPPObject> pointer) {
		super(pointer);
	}
}
